### ISSUE TITLE
Make it possible to gzip and push static assets

### ISSUE THREAD

**Issue by jasongonzales23** [locomotivecms/wagon#151]
This is a two-part feature request.

I would like to be able to configure Wagon to gzip static files somehow. It seems there is already a good rack app for this that might prove useful:

http://artsy.github.io/blog/2012/02/24/10x-rack-and-rails-output-compression-with-rack-deflater/

I think it would be most helpful to make this gzipping happen when 'push' is called.

The big complication here is getting it to work with the local wagon server as well as pushing to S3.

I also realize that this requires configuration on S3, but that is something I am willing to fiddle with in order to get this much needed optimization.

Right now, when I try to do anything with gzip I only get 'invalid byte sequence' errors which I assume are due to limitations of the program right now.

**Comment by jeppeliisberg** [comment]
+1 except that the engine must push both an uncompressed and a compressed version to s3 and  change the request URL based on whether the request includes an `Accept-Encoding: gzip` header. 

see http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#CompressedS3

**Comment by did** [comment]
thanks for the link @jeppeliisberg. But as far as I understand this guide, it looks like that's Cloudfront's responsibility to make a compressed version of the file.
