### ISSUE TITLE
searchable: true

### ISSUE THREAD

**Issue by AlexandreBroudin** [locomotivecms/wagon#155]
If  I add this parameter in any object of yml content_type file, it does not work.
In wagon.log I have :

```[Locomotive::Mounter::Models::ContentField] setting an unknown attribute 'searchable' with the value 'true'```

**Comment by drc37** [comment]
I am seeing this same issue with Wagon 1.5.7.

**Comment by did** [comment]
The searchable attribute is no longer used in Wagon v2.
