### ISSUE TITLE
Pushing a single page

### ISSUE THREAD

**Issue by erwingaitano** [locomotivecms/wagon#170]
Is there a way to push a single page instead of all of them?
The closest approach that makes that possible is deleting the pages I don't want to update and then running:

`bundle exec wagon push development -r pages`

The problem is when I want to keep my changes in the index page. 
I temporally delete the index page (in order to not force it to update), run the above command but get the following error:

`Unable to read the local LocomotiveCMS site. Please check the logs.`

**Comment by did** [comment]
https://github.com/locomotivecms/wagon/commit/a3aaf7e6a7789b1466fea867017ba092f5e9df33
