### ISSUE TITLE
UI Enabled Bug

### ISSUE THREAD

**Issue by jaredklewis** [locomotivecms/wagon#180]
This bug is documented with screenshots in this google discussion: https://groups.google.com/forum/#!topic/locomotivecms/807pJfyrja0

## The Bug
Even when ui_enabled is set to true and in the back-office model-editor, it shows UI enabled as being set to true, the has many editor doesn't show up when adding or editing a content entry.

## Steps to replicate

- 1 - Make two related content types in wagon. For example a *posts* content type and *photos* content type where each post has many photos.

- 2 - Update the field definitions of the related fields to look as follows.

### posts.yml

    - photos: # Name of the field
        label: Photos
        type: has_many
        required: false
        localized: false
        class_name: photos 
        inverse_of: post
        ui_enabled: true

### photos.yml

    - post: # Name of the field
        label: Post # Human readable name of the field
        type: belongs_to
        required: true
        localized: false
        class_name: posts

 - 3 - Push to your engine. 

## Work around
I've found two workarounds to this problem.

1. From the back-office editor, edit the the model of the child type. In this case, photos. Don't change any values, just resave it. Now go to add/edit and post and everything works.

2. Add the attribute *ui_enabled: true* to the post field definition in *photos.yml* and re-push to the Engine.

**Comment by did** [comment]
it shouldn't be an issue in Wagon v2 (Locomotive v3)
