### ISSUE TITLE
wagon serve errors on windows 8.1

### ISSUE THREAD

**Issue by istickz** [locomotivecms/wagon#183]
1-st Error - run serve without path:

<pre>
> bundle exec wagon serve

C:/Ruby200/bin/wagon: No such file or directory - which convert
Can't get the absolute path for the passed directory: ''!
</pre>

2-nd Error - run serve with path(Server runned, but have errors)

<pre>
> bundle exec wagon serve c:/testapp

C:/Ruby200/bin/wagon: No such file or directory - which convert
>> Thin web server (v1.5.1 codename Straight Razor)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:3333, CTRL+C to stop
</pre>

**Comment by greyskin** [comment]
Me too. And so does amadaneus: https://github.com/locomotivecms/wagon/issues/342
