### ISSUE TITLE
Asset Management

### ISSUE THREAD

**Issue by jaredklewis** [locomotivecms/wagon#188]
So, currently, front-end assets in Wagon are not managed.

The closest thing available are the built-in bootstrap and foundation site templates, but these actually are not a good idea. For one thing, between the release cycles for Foundation, Bootstrap, and jQuery, just to keep the templates up to date would require releasing a new version of Wagon every month. Further, once you install a site template, the installed assets must be updated manually. And finally, we're only offering two frameworks out of the hundreds of front-end libraries and tools available. 

So, all in all, I would say Wagon could use a better system. Ideally, we could just enter the names of the assets we want into a file, and they would be installed and updated automatically, as in other frameworks.

Rails uses a gem system. Install the asset's gem (i.e. foundation-rails, jquery-rails, backbone-rails, etc...) and the assets are available and automatically updated upon `bundle update`. I think it would be a mistake to attempt this system (i.e. foundation-wagon, jquery-wagon) etc...because the LocomotiveCMS community is not yet large enough to maintain so many repositories.

The nodejs/front-end crowd uses Bower (http://bower.io) to accomplish the same thing and has a huge number of maintained repos so that users can add just about any asset they like (good luck finding a library/framework not in bower).

I would say, let's not reinvent the wheel and just find a way to add Bower to wagon, except that Bower requires nodejs, which would be adding a non-Gem dependency.

So, then I thought, what about writing a dead-simple asset manager that makes use of the existing bower infrastructure? Every major library or framework (jquery, bootstrap, foundation, backbone, and so  on) already has a bower.json file in their repo.

So, what would everyone think about a feature written in ruby and included with wagon used bower for front end asset management. It would just be simple:
- A yaml file with a list of repo names and version numbers (git://github.com/jquery/jquery.git 1.10, git://github.com/twbs/bootstrap.git 2.3.2, etc... )
- on `wagon assets install` it would install the assets in the file.
- If you want to update the assets, update the version numbers and run `wagon assets install` again.

I don't think the feature should try to do dependency management (i.e. you wanted backbone, that needs underscore, so I'll automatically install that for you too), which is what most of the bower codebase is dedicated to doing. This would keep the code really simple. Download the version of the repo specified (using tags), open bower.json, then copy the files specified in "main" to the appropriate asset folders.

Thoughts? If everyone thinks it's a good idea I might work up a PR for testing.

**Comment by did** [comment]
Welcome to Webpack :-) https://doc.locomotivecms.com/v4.0/docs/manage-js-and-css-with-webpack
