### ISSUE TITLE
Content entry's "visible" attribute should be used by default when iterating through entries

### ISSUE THREAD

**Issue by jloosfelt** [locomotivecms/wagon#197]
The _visible attribute appeared quite lately in Locomotive, and my authors started to use it quite naturally, but it wouldn't work as expected, as my templates just iterate through content entries.
for example
    {% for category in contents.categories %}
    {% endfor %}
will display every entries, visible or not.

Now I have to change any view that display content entries to add a with_scope:
    {% with_scope _visible: true %}
    {% for category in contents.categories %}
    {% endfor %}
    {% endwith_scope %}

Am I missing something? I think this is not a clean way to do this.
I would expect contents.categories to filter the visible entries by default, and have an option to force the iteration through the disable entries as well only if required.
Why not a contents.categories.all or something like that?

What are your thought about this?

**Comment by did** [comment]
it shouldn't be an issue anymore in Wagon v2 (Locomotive v3)
