### ISSUE TITLE
ERB Support

### ISSUE THREAD

**Issue by jaredklewis** [locomotivecms/wagon#198]
In addition to the conciseness of the tags, I've found that one advantage of using HAML is the ability to execute ruby code to reduce repetition in templates.

```
%ol.steps
  -3.times do |count|
    %li
      {% editable_text 'step_#{count}' %}Lorem ipsum{% endeditable_text %}
```

Or

```
- ['jquery', 'foundation', 'lightbox'].each do |script|
  {{ #{script}.min.js | javascript_tag }}
```

Since, not everyone might be drinking the HAML kool-aid, what about adding ERB as an additional preprocessed template option? I still think the default template type should be plain .liquid files, but adding .liquid.erb as an option allows those not familiar with HAML take advantage of pre-processed ruby.

Like HAML these templates wouldn't ever make it to the server. They would be preprocessed into Liquid on deployment.

Thoughts?

**Comment by did** [comment]
I don't want to bring in too many different templating languages. Liquid could handle this (at least the second example). Regarding the first one, sections (https://doc.locomotivecms.com/v4.0/docs) should be perfect for this use case.
