### ISSUE TITLE
Can't deploy site locally 

### ISSUE THREAD

**Issue by alvinkatojr** [locomotivecms/wagon#207]
I get the following error when attempting to deploy my locomotive site locally:
<code>unable to get an API token: Connection refused - connect(2) for "localhost" port 8000</code>

But when I change the host to locomotivehosting, the deployment is a success. What could be the problem?

**Comment by did** [comment]
I'm closing it since a lot of things have been changed in Wagon v2 (Locomotive V3)

**Comment by alvinkatojr** [comment]
No worries @did. This was like 2 years ago and everything is running fine. I should have mentioned that ages ago. Thanks for the help!
