### ISSUE TITLE
Using locale_switcher with "label: locale" results in "translation missing" errors

### ISSUE THREAD

**Issue by organsnyder** [locomotivecms/wagon#218]
#### Steps to reproduce
1. Add {% locale_switcher label: 'locale' %} tag to page

#### Expected behavior
Locale switcher with localized language labels

#### Actual behavior
"translation missing" errors for en.locales.es, en.locales.en, es.locales.en, etc.

**Comment by did** [comment]
thanks @organsnyder :+1:
