### ISSUE TITLE
Problems installing wagon in Windows: "Serve" not running

### ISSUE THREAD

**Issue by carolamigo** [locomotivecms/wagon#220]
Hello, I installed Wagon and its gem's dependencies without problems in Windows 8.1, but when I enter the command: $ bundle exec wagon serve, I do not get any message back. I was suppose to get this according to the guide:

$ bundle exec wagon serve
>> Thin web server (v1.5.1 codename Straight Razor)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:3333, CTRL+C to stop 

Because of that I am not being able to preview my website though the address http://localhost:3333. Does anybody know what went wrong?

**Comment by meligatt** [comment]
Hi carolamigo, any ideas about the problem? I'm getting the same error. I'm running locomotivecsm in a windows 7 machine and I'm not getting any output when I run $ bundle exec wagon serve

**Comment by meligatt** [comment]
Hi did this is the line in my LOG file 
uninitialized constant Class::TZInfo
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:366:in `rescue in []'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:364:in `[]'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:337:in `new'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_mounter-1.5.0/lib/locomotive/mounter/reader/file_system/site_reader.rb:18:in `block in read'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_mounter-1.5.0/lib/locomotive/mounter/reader/file_system/site_reader.rb:16:in `tap'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_mounter-1.5.0/lib/locomotive/mounter/reader/file_system/site_reader.rb:16:in `read'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_mounter-1.5.0/lib/locomotive/mounter/reader/runner.rb:76:in `block (2 levels) in build_mounting_point'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_mounter-1.5.0/lib/locomotive/mounter/reader/runner.rb:73:in `each'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_mounter-1.5.0/lib/locomotive/mounter/reader/runner.rb:73:in `block in build_mounting_point'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_mounter-1.5.0/lib/locomotive/mounter/reader/runner.rb:70:in `tap'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_mounter-1.5.0/lib/locomotive/mounter/reader/runner.rb:70:in `build_mounting_point'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_mounter-1.5.0/lib/locomotive/mounter/reader/runner.rb:29:in `run!'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_wagon-1.5.1/lib/locomotive/wagon.rb:261:in `require_mounter'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_wagon-1.5.1/lib/locomotive/wagon.rb:75:in `serve'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_wagon-1.5.1/lib/locomotive/wagon/cli.rb:249:in `serve'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/locomotivecms_wagon-1.5.1/bin/wagon:12:in `<top (required)>'
	C:/Bitnami/rubystack-1.9.3-27/ruby/bin/wagon:23:in `load'
	C:/Bitnami/rubystack-1.9.3-27/ruby/bin/wagon:23:in `<main>'

**Comment by carolamigo** [comment]
I could not fix it, I ended up installing Locomotive in a Ubuntu virtual
machine using VMware.


Carolina Amigo
about.me/carolina.amigo
  [image: Carolina Amigo on about.me]

<http://about.me/carolina.amigo>

**Comment by did** [comment]
hey @carolamigo, I'm glad you found a solution to make it work with Windows. Hope it will help others. thanks!

**Comment by ulitiy** [comment]
Well it's not quite a solution, wagon just doesn't start natively on windows, 2 colleagues tried, no result, the same output and wagon.log. With your gemfile the same.

**Comment by enriquesalceda** [comment]
Hi @did,

I'm having a similar problem in Mac. I'm working with the "Quick start" documentation from the site. Following the instructions I reached the point were I have to launch the server, I ran the command `bundle exec wagon serve`, but it fails. I have the following outcome:

```
MyPortfolio % bundle exec wagon serve 
[Dragonfly] !disabled!
[Dragonfly] If you want to take full benefits of all the features in Locomotive Steam, we recommend you to install ImageMagick. Check out the documentation here: http://doc.locomotivecms.com.

Your site is served now.
Browse http://0.0.0.0:3333
```
Following your comments above I tried to find my `log/` directory, but I don't have it. When I run the command `ls -l` on my directory I can see the following:

```
total 40
-rw-r--r--  1 enriquesalceda  staff   636 29 Feb 23:56 Gemfile
-rw-r--r--  1 enriquesalceda  staff  3945 29 Feb 23:56 Gemfile.lock
-rw-r--r--  1 enriquesalceda  staff   558 29 Feb 23:56 Guardfile
drwxr-xr-x  4 enriquesalceda  staff   136 29 Feb 23:56 app
drwxr-xr-x  5 enriquesalceda  staff   170 29 Feb 23:56 config
drwxr-xr-x  2 enriquesalceda  staff    68 29 Feb 23:56 data
-rw-r--r--  1 enriquesalceda  staff    66 29 Feb 23:58 dragonfly.log
-rw-r--r--  1 enriquesalceda  staff  2783 29 Feb 23:56 icon.png
drwxr-xr-x  6 enriquesalceda  staff   204 29 Feb 23:56 public
```
As you can see the is not `log/` directory. Obviously, when I run `ls: log/*`, I receive this error:

```
ls: log/*: No such file or directory
```
 What is going wrong with my installation, I followed the instructions.

Cheers.

**Comment by enriquesalceda** [comment]
Manually I created the directory and the file, and I can see a bootstrap site. I hope that fixes the problem.

**Comment by Eneldo23** [comment]
Hi @carolamigo what version of ubuntu did you use to install locomotive?
