### ISSUE TITLE
Foundation5 template not working with SASS/SCSS?

### ISSUE THREAD

**Issue by estiens** [locomotivecms/wagon#225]
1) `init`ed a new site using the foundation-5 template using HAML and SCSS
2) `wagon serve`

No CSS is being rendered
![screen shot 2015-01-05 at 5 26 34 pm](https://cloud.githubusercontent.com/assets/4022668/5621871/7f03d3a6-9500-11e4-87b9-058d42f83cb8.png)

**Comment by estiens** [comment]
Upon looking at the compiled application.css, it appears none of the foundation scss files are being imported, it only has the normalize.css in it

**Comment by did** [comment]
thanks @estiens ! Wait for Wagon 1.5.2.
