### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by amalagaura** [locomotivecms/wagon#231]
I am running with Ruby 2.2.0. I did a fresh `wagon init`, added the deploy.yml and tried to push. If I leave ssl: true I get the following error

`unable to get an API token: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure`

Following is my Gemfile.lock. I tried to `bundle update` as well.
https://gist.github.com/amalagaura/67be9fc1c196bea6f30e

**Comment by did** [comment]
hey @amalagaura , which system are u running Wagon on?

**Comment by amalagaura** [comment]
OSX 10.10.2 with ruby 2.2.0p0 from RVM

**Comment by did** [comment]
Sorry, been busy. what does this command return if you type it in your terminal?
````ruby -ropenssl -rpp -e "pp OpenSSL::SSL::SSLContext::METHODS"````

**Comment by amalagaura** [comment]
```
ruby -ropenssl -rpp -e "pp OpenSSL::SSL::SS

LContext::METHODS"
[:TLSv1,
 :TLSv1_server,
 :TLSv1_client,
 :TLSv1_2,
 :TLSv1_2_server,
 :TLSv1_2_client,
 :TLSv1_1,
 :TLSv1_1_server,
 :TLSv1_1_client,
 :SSLv3,
 :SSLv3_server,
 :SSLv3_client,
 :SSLv23,
 :SSLv23_server,
 :SSLv23_client]
```

**Comment by did** [comment]
@amalagaura , I think I know where the error comes from. A lot of systems seem to disable SSLv3 because it's not proven secure anymore. It has to be replaced by TLSv1_2. I'm going to fix it.
Quick question: what's the target you deploy your site to? The hosting platform or your own server?
Thanks!

**Comment by did** [comment]
good news! There is a simple workaround :-)
In the config/deploy.yml file of your Wagon site, you can specify the version of SSL you want to use like this:

````hosting:
  host: <mysite>.locomotivehosting.com
  api_key: <my api key>
  ssl: true
  ssl_version: TLSv1_2```

In the meantime, I'm going to change the default SSL version if Wagon.

**Comment by amalagaura** [comment]
I was actually bitten by this with a separate provider. When SSLv3 was announced as insecure some providers turned it off and things we were using stopped working. The rest-client gem had SSLv3 as a default. But in that case, not specifying the SSL method made it choose a proper protocol. Anyway thanks for looking at that, now the README instructions should work for everyone.
