### ISSUE TITLE
I cannot push my website after adding translations

### ISSUE THREAD

**Issue by bsylvain** [locomotivecms/wagon#235]
I have added languages to my website and now when I Push there is the following error for all the new locales : 

     en
        updating index..............................................................[done]
        updating sous-categories....................................................[not translated (itself or parent)]
        updating 404................................................................[done]
    Warning: NOT all the pages were pushed.
	    Check that the pages inheritance was done right OR that you translated all your pages.

I am not sure what that mean, what should I do?

**Comment by did** [comment]
if you've got 2 locales, then you need to have 2 versions of each page, one for each locale.
Example: (if fr is not the default locale)
**index.liquid** and **index.fr.liquid**

**Comment by adam-pl** [comment]
Ok, thank you @did for the info.
Now I use one template after some templates refactoring.
