### ISSUE TITLE
Pushing with wagon doesn't update completely

### ISSUE THREAD

**Issue by nicovalero** [locomotivecms/wagon#238]
Hello!
I have been working with wagon in local, but a weird error happens when trying to push to engine, that is in the Internet: It doesn't update all the content of a page, just some parts (exactly, I got updated the title section and not anymore). By the way, everything goes fine and it doesn't appear any error.
I tried adding the force flag (-f), but nothing happens.

Does anyone know why this might be happening?

Thanks!

**Comment by did** [comment]
In Wagon v2, deploying an existing page with Wagon will only change the template. However, the -d option will update the content of the editable_elements if specified in the YAML header of the page.
