### ISSUE TITLE
Various errors when pushing

### ISSUE THREAD

**Issue by JacobEvelyn** [locomotivecms/wagon#239]
We're seeing strange behavior today where pushing produces a number of errors. It appears to be nondeterministic in terms of which errors we see, but we've tried dozens of times and `bundle exec wagon push` has never worked. Here are some of the errors we're seeing:

```ruby
error => undefined method `[]' for nil:NilClass (NoMethodError)
```
```ruby
error => Expected(201) <=> Actual(422 Unprocessable Entity)
```
```ruby
error => SSL_write:: bad write retry (OpenSSL::SSL::SSLError)
```
We've tried this with a known stable state of the code and no luck. Is there anything we could try?

**Comment by stunjiturner** [comment]
error => undefined method `[]' for nil:NilClass (NoMethodError)

i ma seeing this as well

**Comment by stunjiturner** [comment]
anybody, anything?

**Comment by did** [comment]
Assuming you push your site to an engine running with SSL, could you add this in your config/deploy.yml file?

    somewhere:
      host: xxxx
      api_key: xxx
      ssl: true
      ssl_version: TLSv1_2

About **Actual(422 Unprocessable Entity)**. You should have a list of errors below this message. 

Actually, could you just post here the whole output of the push command please?

**Comment by stunjiturner** [comment]
error => undefined method `[]' for nil:NilClass (NoMethodError). What's the fix for this error?

**Comment by stunjiturner** [comment]
UPDATE:
added   gem 'locomotivecms_liquid_extensions', github: 'locomotivecms/liquid_extensions', ref: 'd46c7e4', branch: 'hosting' to my engine, and everything pushes and pulls properly. Notice that locomotivecms_liquid_extensions is using the hosting branch, hope this helps fixes

 error => undefined method `[]' for nil:NilClass (NoMethodError) on your machine

@JacobEvelyn

**Comment by JacobEvelyn** [comment]
Thanks for the info! This issue resolved itself after a few days as mysteriously as it appeared. If it happens again I'll give this a shot!

**Comment by stunjiturner** [comment]
I having issues with pulling a site in version 2.5.6 of the locomotive engine:

 writing undefined method `translated_in' for nil:NilClass , when the Log file is Writing Pages, is shows up after the last final page template shows done, So it seems like its looking for more pages and there not anymore. at least in the backend ui view?

**Comment by stunjiturner** [comment]
I found the problem, some of my sites hosted on heroku, do not have a page not found (404) page, in the backend UI. When the wagon tries to pull the 404 page it chokes with the aforementioned error. Any Suggestions??

**Comment by did** [comment]
What about with Wagon v2 and Engine v3?
