### ISSUE TITLE
No such file or directory - /var/tmp/dragonfly.log

### ISSUE THREAD

**Issue by dimanyc** [locomotivecms/wagon#240]
Getting the `No such file or directory - /var/tmp/dragonfly.log` error message when trying to access assets from the `Public` folder. I am running Wagon on Win 8.1, Ruby v2.0.0p451 (2014-02-24) [i386-mingw32], Rails 4.1.6.

**Comment by dimanyc** [comment]
ended up installing the Bitnami Ruby Stack.

**Comment by did** [comment]
thanks @dimany for posting your solution here.
