### ISSUE TITLE
Wagon server not reloading changed views

### ISSUE THREAD

**Issue by jimzar** [locomotivecms/wagon#241]
I change my views but wagon server doesn't update them and I have to restart the server. Is there any solution to this ?

**Comment by jimzar** [comment]
Also if I delete a file wagon doesn't understand anyting. It seems that everything is cached and doesn't communicate with filesystem

**Comment by did** [comment]
hi @jimzar,

Could you take a look at the logs file (log/wagon.log) please? Check if you find something similar to:

````* Reloaded "pages", "snippets" at 2015-05-10 17:32:25 +0200````

If not, then it would mean that the fs-event lib does not work correctly.

**Comment by jimzar** [comment]
hi @did .

My wagon.log file includes the following:

```

[0m
[0;31;49m[Important] YUICompressor requires java to be installed. The JAVA_HOME variable should also be set.
[0m
[0;97;49mStarted GET "/" at 2015-05-10 20:20:20 +0300[0m
Detecting locale EN
Found page "Home" [index]
  Rendered snippet header
  Rendered snippet footer
  Rendered liquid page template
[0;32;49mCompleted 200 OK in 5.3ms

[0m
[0;97;49mStarted GET "/" at 2015-05-10 20:20:20 +0300[0m
Detecting locale EN
Found page "Home" [index]
  Rendered snippet header
  Rendered snippet footer
  Rendered liquid page template
[0;32;49mCompleted 200 OK in 6.3ms

[0m
```

As I see it doesn't include what you wrote in your comment. Are there any suggestions to solve this problem?

**Comment by jimzar** [comment]
@did I just fixed it! I had uninstalled Xcode and for some reason it stopped working. I installed it again today and everything works fine now :)
So I would suggest you to add a note somewhere that xcode needs to be installed.

**Comment by manuchap** [comment]
The command line tools should suffice though:
https://developer.apple.com/downloads/index.action#
