### ISSUE TITLE
Not returning parent handle

### ISSUE THREAD

**Issue by jimzarkadas** [locomotivecms/wagon#242]
For some reason i can get parent.slug in my view but nothing returns when i call parent.handle.

Any ideas why this happens ?

**Comment by did** [comment]
@jimzar Which version are you using? (v1.5.x or the v2.alpha)

**Comment by jimzar** [comment]
1.5.4 and engine 2.5.6.

**Comment by did** [comment]
Fixed in Wagon v2.
