### ISSUE TITLE
bundle exec wagon serve not working

### ISSUE THREAD

**Issue by josephx1a** [locomotivecms/wagon#245]
when i run ```$ bundle exec wagon serve``` from the root of the project directory i am met with this error ```Celluloid 0.17.0 is running in BACKPORTED mode. [ http://git.io/vJf3J ] wrong number of arguments (2 for 1)``` 

i can't seem to find a fix for this anywhere? Please advise!

**Comment by P3t3rU5** [comment]
Hi @josephx1a

I had this exact same error yesterday.

For now I'd advise you to change `Gemfile.lock` to a previous version. I know it's not the perfect solution but it worked for me.

Change all the celluloid references in the file to this:

```
celluloid (0.16.0)
  timers (~> 4.0.0)
```

**Comment by josephx1a** [comment]
Yikes! It worked but you're right not the most ideal solution! Thanks for the fast reply! Hopefully we can get an official explanation/fix soon!

**Comment by scarl3tt** [comment]
I also had that issue, but instead of making the bandaid fix of changing the celluloid version in `Gemfile.lock`, I specified 0.16.0 in `Gemfile`. It's much neater, especially since (I assume) you're not source controlling `Gemfile.lock`.

**Comment by P3t3rU5** [comment]
@scarl3tt I thought it was an hard dependency in any gem that LocomotiveCMS requires so i assumed that even if I edited the Gemfile the hard dependecy would overwrite whatever I would put the Gemfile.

**Comment by scarl3tt** [comment]
This is from an operational Gemfile. The changes made in my fork are to address non-related issues.
```
gem 'locomotivecms_wagon', '1.5.5', :github => 'scarl3tt/wagon', :branch => 'v1.5.x'

# Newer versions of celluloid break literally all of the things
gem 'celluloid', '~> 0.16.0'
```

**Comment by did** [comment]
thanks guys! I'll release the 1.5.7 version later today.
