### ISSUE TITLE
Get Error

### ISSUE THREAD

**Issue by philipheinser** [locomotivecms/wagon#248]
``
uninitialized constant Class::TZInfo
	/Users/philipheinser/.gems/gems/activesupport-3.2.22/lib/active_support/values/time_zone.rb:367:in `rescue in []'
	/Users/philipheinser/.gems/gems/activesupport-3.2.22/lib/active_support/values/time_zone.rb:365:in `[]'
	/Users/philipheinser/.gems/gems/activesupport-3.2.22/lib/active_support/values/time_zone.rb:338:in `new'
	/Users/philipheinser/.gems/gems/locomotivecms_mounter-1.5.5/lib/locomotive/mounter/reader/file_system/site_reader.rb:18:in `block in read'
	/Users/philipheinser/.gems/gems/locomotivecms_mounter-1.5.5/lib/locomotive/mounter/reader/file_system/site_reader.rb:16:in `tap'
	/Users/philipheinser/.gems/gems/locomotivecms_mounter-1.5.5/lib/locomotive/mounter/reader/file_system/site_reader.rb:16:in `read'
	/Users/philipheinser/.gems/gems/locomotivecms_mounter-1.5.5/lib/locomotive/mounter/reader/runner.rb:76:in `block (2 levels) in build_mounting_point'
	/Users/philipheinser/.gems/gems/locomotivecms_mounter-1.5.5/lib/locomotive/mounter/reader/runner.rb:73:in `each'
	/Users/philipheinser/.gems/gems/locomotivecms_mounter-1.5.5/lib/locomotive/mounter/reader/runner.rb:73:in `block in build_mounting_point'
	/Users/philipheinser/.gems/gems/locomotivecms_mounter-1.5.5/lib/locomotive/mounter/reader/runner.rb:70:in `tap'
	/Users/philipheinser/.gems/gems/locomotivecms_mounter-1.5.5/lib/locomotive/mounter/reader/runner.rb:70:in `build_mounting_point'
	/Users/philipheinser/.gems/gems/locomotivecms_mounter-1.5.5/lib/locomotive/mounter/reader/runner.rb:29:in `run!'
	/Users/philipheinser/.gems/gems/locomotivecms_wagon-1.5.5/lib/locomotive/wagon.rb:262:in `require_mounter'
	/Users/philipheinser/.gems/gems/locomotivecms_wagon-1.5.5/lib/locomotive/wagon.rb:75:in `serve'
	/Users/philipheinser/.gems/gems/locomotivecms_wagon-1.5.5/lib/locomotive/wagon/cli.rb:272:in `serve'
	/Users/philipheinser/.gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/philipheinser/.gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/philipheinser/.gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/philipheinser/.gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/philipheinser/.gems/gems/locomotivecms_wagon-1.5.5/bin/wagon:12:in `<top (required)>'
	/Users/philipheinser/.gems/bin/wagon:23:in `load'
	/Users/philipheinser/.gems/bin/wagon:23:in `<main>'
``

**Comment by cema-sp** [comment]
I've had similar issue with wagon 2.0.0.rc1. How do you run wagon? W/ or w/o bundler?

**Comment by manuchap** [comment]
Might be du to lazy loading of tzinfo in rails.
Try uninstalling ALL tzinfo gems and re-install it or load it before your app:
environement.rb:
`
# adding this fixes the issue
require 'tzinfo'

# Load the Rails application.
require File.expand_path('../application', __FILE__)

# Initialize the Rails application.
Rails.application.initialize!
`

**Comment by did** [comment]
always use bundler to run commands inside a Wagon site folder.
