### ISSUE TITLE
Working on Locomotive CMS on Cloud IDE

### ISSUE THREAD

**Issue by superkarolis** [locomotivecms/wagon#252]
Hi there,

The tutorial is very clear about how to get the site working on localhost and deploy it to Locomotivehosting. But does anyone know whether it's possible to set up Locomotive CMS to work on Cloud IDE such as C9 and then deploy to custom server too?

**Comment by did** [comment]
that's a super interesting topic. Unfortunately, I don't have time right now to investigate more...

**Comment by manuchap** [comment]
Deploying to Heroku from C9 as I type. Pretty straightforward.
Two ways actually, using a v3@heroku and according to the app's deploy tab:
• install heroku toolbelt in you vm and use it as usual.
• push to a github repo using the [https://github.com/integrations/heroku-custom-deploy](heroku-custom-deploy) integration.

**Comment by did** [comment]
@manuchap Would it be possible to code your Wagon site in Cloud C9 and deploy the changes automatically (so running the ````wagon deploy````command behind the scene) to a Locomotive engine?

**Comment by manuchap** [comment]
I'm gonna try this next. Right now I've gone a much simpler way (my goal being editing the engine).
Heroku has a pretty tight integration with github. Once a repo is linked, you can choose which branch to push automatically to heroku on each commit.

**Comment by cerdiogenes** [comment]
Yes, it's possible! I'm using fog to coordinate servers on AWS and docker to deploy c9 containers to these machines, it's working pretty well, but not without some roughes #340.
