### ISSUE TITLE
wagon push fails with fontawesome

### ISSUE THREAD

**Issue by nurbs999** [locomotivecms/wagon#253]
When I try to push my site to locomotivecms it always failes on .eot files from fontawesome.

    bundle exec wagon push production
    * Pushing Site
    * Pushing Snippets
        de
    * Pushing ContentTypes
    * Pushing Pages
        de
       updating index..............................................................[done]
       updating 404................................................................[done]
    * Pushing ThemeAssets
       updating images/stinker_elektro.jpg.........................................[same]
       updating images/video.jpg...................................................[same]
       creating font-awesome/fonts/fontawesome-webfont.eot{"local_path"=>["nicht verfügbar"]}

ruby version:

     ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

installed gems

    *** LOCAL GEMS ***

    activesupport (3.2.22)
    better_errors (1.0.1)
    bigdecimal (1.2.4)
    bundler (1.7.6)
    bundler-unload (1.0.2)
    celluloid (0.16.0)
    chronic (0.10.2)
    chunky_png (1.3.4)
    coderay (1.1.0)
    coffee-script (2.2.0)
    coffee-script-source (1.9.1.1)
    colorize (0.5.8)
    commonjs (0.2.7)
    compass (1.0.3)
    compass-core (1.0.3)
    compass-import-once (1.0.5)
    daemons (1.2.3)
    dragonfly (0.9.15)
    erubis (2.7.0)
    eventmachine (1.0.7)
    execjs (2.5.2)
    executable-hooks (1.3.2)
    faker (0.9.5)
    ffi (1.9.10)
    gem-wrappers (1.2.7)
    haml (4.0.6)
    hike (1.2.3)
    hitimes (1.2.2)
    httmultiparty (0.3.10)
    httparty (0.13.5)
    i18n (0.6.11)
    io-console (0.4.2)
    json (1.8.3, 1.8.1)
    less (2.2.2)
    listen (2.7.12)
    locomotivecms-liquid (2.6.0)
    locomotivecms-solid (0.2.2.1)
    locomotivecms_mounter (1.5.6)
    locomotivecms_wagon (1.5.7)
    logger (1.2.8)
    mime-types (1.25.1)
    minitest (4.7.5)
    multi_json (1.8.4)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    netrc (0.7.9)
    psych (2.0.5)
    rack (1.6.4)
    rack-cache (1.2)
    rack-livereload (0.3.16)
    rake (10.1.0)
    rb-fsevent (0.9.5)
    rb-inotify (0.9.5)
    rdoc (4.1.0)
    redcarpet (3.0.0)
    RedCloth (4.2.9)
    rubygems-bundler (1.4.4)
    rubyzip (1.1.7)
    rvm (1.11.3.9)
    sass (3.4.16)
    sprockets (2.12.4)
    sprockets-sass (1.2.0)
    stringex (2.0.11)
    test-unit (2.1.5.0)
    thin (1.6.3)
    thor (0.19.1)
    tilt (1.4.1)
    timers (4.0.1)
    tzinfo (0.3.44)
    wdm (0.1.1)
    will_paginate (3.0.7)
    yui-compressor (0.12.0)
    zip (2.0.2)

**Comment by did** [comment]
Works fine with Wagon v2 and Engine v3.
