### ISSUE TITLE
bundle install fails because of event machine

### ISSUE THREAD

**Issue by JerryTheMouse** [locomotivecms/wagon#261]
I've been following this [tutorial] (http://doc.locomotivecms.com/making-blog/1-1-create-wagon-site), but bundle install always fails (specifically event machine 1.0.3)
I tried installing event machine via gem it installed version 1.0.8 without problems. 
So is there is away to install 1.0.3 or to upgrade locomotive dependency to 1.0.8

	    Installing eventmachine 1.0.3 with native extensions

	Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

	/usr/bin/ruby -r ./siteconf20151001-30246-5fvukt.rb extconf.rb --with-cflags='-O2 -pipe -march=native -w'
	checking for rb_trap_immediate in ruby.h,rubysig.h... no
	checking for rb_thread_blocking_region()... no
	checking for inotify_init() in sys/inotify.h... yes
	checking for writev() in sys/uio.h... yes
	checking for rb_wait_for_single_fd()... yes
	checking for rb_enable_interrupt()... no
	checking for rb_time_new()... yes
	checking for sys/event.h... no
	checking for epoll_create() in sys/epoll.h... yes
	creating Makefile

	make "DESTDIR=" clean

	make "DESTDIR="
	compiling pipe.cpp
	compiling rubymain.cpp
	compiling page.cpp
	compiling binder.cpp
	compiling ssl.cpp
	compiling ed.cpp
	compiling cmain.cpp
	compiling kb.cpp
	kb.cpp: In member function ‘virtual void KeyboardDescriptor::Read()’:
	kb.cpp:77:27: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
	  read (GetSocket(), &c, 1);
				   ^
	compiling em.cpp
	em.cpp: In member function ‘void EventMachine_t::_RunEpollOnce()’:
	em.cpp:574:37: error: ‘rb_thread_select’ was not declared in this scope
	   EmSelect (0, NULL, NULL, NULL, &tv);
					     ^
	em.cpp: In member function ‘int SelectData_t::_Select()’:
	em.cpp:827:67: error: ‘rb_thread_select’ was not declared in this scope
	  return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
									   ^
	em.cpp: In member function ‘void EventMachine_t::_RunSelectOnce()’:
	em.cpp:946:40: error: ‘rb_thread_select’ was not declared in this scope
	      EmSelect (0, NULL, NULL, NULL, &tv);
						^
	em.cpp: In member function ‘void EventMachine_t::SignalLoopBreaker()’:
	em.cpp:282:34: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
	  write (LoopBreakerWriter, "", 1);
					  ^
	em.cpp: In member function ‘void EventMachine_t::_ReadLoopBreaker()’:
	em.cpp:991:50: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
	  read (LoopBreakerReader, buffer, sizeof(buffer));
							  ^
	Makefile:229: recipe for target 'em.o' failed
	make: *** [em.o] Error 1

	make failed, exit code 2

	Gem files will remain installed in /home/jerry/.gem/ruby/2.2.0/gems/eventmachine-1.0.3 for inspection.
	Results logged to /home/jerry/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/eventmachine-1.0.3/gem_make.out
	An error occurred while installing eventmachine (1.0.3), and Bundler cannot continue.
	Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.

**#update 1**
I cloned the repo from the tutorial and it uses old version of locomotive.
When I create a new locomotive project via 
  
    wagon init 

it worked and used eventmachine 1.0.8

**Comment by manuchap** [comment]
Not sure it's related but I'm on mac and el capitan (osx.11) dropped support for openssl so in my case I had to:
`gem install eventmachine -v '1.0.8' -- --with-cppflags=-I/usr/local/opt/openssl/include`
to compile it.

**Comment by did** [comment]
thanks @manuchap :-)

**Comment by TylerSangster** [comment]
+1 
thank you @manuchap

**Comment by przbadu** [comment]
thanks @manuchap
