### ISSUE TITLE
Overwrite editable_text with text from template.

### ISSUE THREAD

**Issue by sasa-friedrich-bitlab** [locomotivecms/wagon#263]
How can I overwrite editable_text with the one from template after editing in BackOffice?

I tried it with 

`bundle exec wagon push production --data --force`

but no luck. Is it even possible?

Thank you 4 help!

**Comment by sasa-friedrich-bitlab** [comment]
I found a way, but it's quite intrusive. I can run rails console on engine and copy text from page's template to editable_element(s).

Is it only way or am I missing something more "user friendly"?

**Comment by manuchap** [comment]
Have you tried adding you editable elements data in your views?
index.liquid
```liquid
---
title: Home
listed: true
published: true
cache_strategy: none
response_type: text/html
position: 0
editable_elements:
  main/txt-1: ! "<h2 class=\"featurette-heading\">First featurette heading. <span
    class=\"text-muted\">It'll blow your mind.</span></h2>\r\n        <p class=\"lead\">Donec
    ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis
    euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur.
    Fusce dapibus, tellus ac cursus commodo.</p>"
---
<!DOCTYPE html>
etc...
