### ISSUE TITLE
New Wagon CLI command: wagon delete

### ISSUE THREAD

**Issue by boie0025** [locomotivecms/wagon#264]
New wagon CLI command:

Usage: wagon delete <resource type> <resource id>

Description:

Delete a resource (page, content_type, content_entries, snippets, theme_assets, ...etc) described by its id (or slug).
The command will ask for a confirmation.

Example: wagon delete content_type articles

<resource id> can be either an ID or a slug.

**Comment by boie0025** [comment]
Content Entries: `wagon delete content_entries posts/my-first-post`

**Comment by CedricLor** [comment]
What would be awesome would even to be able to delete a whole site with this command. In debugging mode, I spend time pushing new sites to the Engine. If I could just delete them with CLI, that would be awesome.

Ex.:
`$ wagon delete site lignthing-blue-2345`

**Comment by did** [comment]
Here is the syntax to delete a site:
````
$ wagon delete <ENV> site
````

**Comment by CedricLor** [comment]
@did thanks for this
