### ISSUE TITLE
bootstrap glyphicons not showing neither on Wagon nor on Engine

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/wagon#268]
Glyphicons are not showing, neither in the Wagon nor in the Engine.

The workaround: go to the file

     /public/stylesheets/bootstrap/_variables.scss
Set the variable

      $icon-font-path: "bootstrap/fonts/" !default;
to

      $icon-font-path: "../fonts/" !default;

and it will work on the Engine. To make them work on the Wagon:

      $icon-font-path: "../../fonts/" !default;

but this won't solve the issue on the Engine.

**Comment by CedricLor** [comment]
I have been working with the latest version of the Wagon for a couple of days. The problem with the Bootstrap glyphicons re-appeared.

My work around is as follows:
In bootstrap.scss, at the beginning, before the @import declaration:
       $icon-font-path: "/fonts/bootstrap/";

In _glyphicons.scss, at the beginning, insert a new line:
       $spec-font-path: $icon-font-path;
Further down, in the woff2 declaration, do:
            url(if($bootstrap-sass-asset-helper, twbs-font-path('#{$spec-font-path}#{$icon-font-name}.woff2'), '..#{$spec-font-path}#{$icon-font-name}.woff2')) format('woff2'),

**Comment by did** [comment]
Have you tried the very last commit of Wagon and generate a brand new site with the bootstrap template?
I ran some tests and I was able to display a glyphicon in Wagon and it was also displayed in Engine after a deployment.
https://github.com/locomotivecms/wagon/blob/master/generators/bootstrap/public/stylesheets/bootstrap.scss#L12.

**Comment by CedricLor** [comment]
Hey @did your fix works great on the Wagon. Will try on the Engine if I can get it working.

**Comment by CedricLor** [comment]
Works great in the Engine also! Thanks a lot, @did !!!
