### ISSUE TITLE
locale_switcher does not work on Wagon 2

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/wagon#271]
I could not make the {{ locale_switcher }} tag on Wagon 2 (nor on the Engine v.3).

Here is my workaround in case anyone needs it:

          <ul class="dropdown-menu">
            {% for locale_string in locales %}
              {% assign locale_string = locale_string | strip | strip_newlines %}
              {% assign locale = locale | strip | strip_newlines %}
              {% unless locale_string == locale %}
                <li><a href="/{{ locale_string }}/{{ page.fullpath }}">{{ locale_string | translate }}</a></li>
              {% endunless %}
            {% endfor %}
          </ul>

**Comment by did** [comment]
Hi @CedricLor, what's the issue about using {{ locale_switcher }}? 500 error page or wrong display? thanks!

**Comment by CedricLor** [comment]
The trouble actually comes from the old documentation.
In this document http://doc.locomotivecms.com/references/i18n, it is mentioned that locale_switcher should be used as follows: 

     {{ locale_switcher label: title, sep: ">>" }}

locale_switcher is a tag, so it should read:

    {% locale_switcher label: locale, sep: ">>" %}

With the correct syntax, it actually works... :+1: 

But... where do you define the locale that you pass to the label. On my end, it does display the fancy name of the corresponding language but the iso name.

Many thanks, @did !!!

**Comment by did** [comment]
@CedricLor please use the new version of the documentation: https://locomotive-v3.readme.io/v1.0/docs/tags#locale_switcher :-)

Concerning your last issue, it's a mistake in the documentation (doc updated). You should write this instead:

````
{% locale_switcher label: 'locale', sep: '>>' %}
````

thanks!

**Comment by CedricLor** [comment]
@did thanks.

Last syntax works, but...

I would expect it to display the language in their translated versions (if I am French and visiting a Chinese website, I would not be able to understand the Chinese people write French).

It is actually not doing it, it displays the names of the languages in the current locale language (i.e. Chinese is written in English in if I am on the English page).
In addition, it misses the zh-CN key (English>>French>>Russian>>translation missing: en.locomotive.locales.zh-CN).
I would expect it to display something like English>>Français>>Русе>>中文

I have this in my translation.yml file.

    en:
      fr: "English"
      en: "English"
      ru: "English"
      zh-CN: "English"

    fr:
      en: "Français"
      fr: "Français"
      ru: "Français"
      zh-CN: "Français"

    ru:
      en: "Русе"
      fr: "Русе"
      ru: "Русе"
      zh-CN: "Русе"

    zh-CN:
      en: "中文"
      fr: "中文"
      ru: "中文"
      zh-CN: "中文"

**Comment by CedricLor** [comment]
Not sure the issues on locale_switcher are completely closed... https://github.com/locomotivecms/wagon/issues/279

Lot's of translation missing issues... translation missing: en.locomotive.locales.zh-CN and others as described here https://github.com/locomotivecms/wagon/issues/279

**Comment by CedricLor** [comment]
OK. Got it.

Translations missing messages come from the fact that steam/config/locales/en.yml and the other translation files do not have zh-CN keys and the locale_switcher is looking for these keys.

In this case, the Wagon config/site.yml should not mention that it accepts zh-CN as a locale.

Thanks
