### ISSUE TITLE
nav tag does not work on Wagon 2

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/wagon#272]
I could not make {% nav %} work on Wagon v.2 (nor on the Engine).

I have the following structure:

    "layouts/simple"
            + --- index
            + --- news
            + --- about

All three are published, listed and positioned.

Both

       {% nav site, depth: 1 %}

and

       {% nav parent, depth: 1 %}

produce the expected result in Wagon v.2 (produces links to "news" and "about").

However, in Engine v.3, my "news" page does not appear to have a parent, nor a depth. I have tried changing the parent of my "news" page but that does not solve the problem.

As a consequence and in both cases, the {% nav %} only outputs one link (to "about").

In addition, the code proposed by the app generator has the same issue.

Here is the code I propose to solve the issue (subject to amendments, depending on the structure of the site) on Engine v3:

        {% for page_in_nav in site.pages %}
          {% if page_in_nav.depth == 0 or page_in_nav.depth == 1 or page_in_nav.depth == null %}
          {% comment %} depth == 0 catches index, depth == 1 catches about, depth == null catches news {% endcomment %}
            <li class="{% if page.slug == page_in_nav.slug %}active{% endif %}">
              {% link_to page_in_nav %}
            </li>
          {% endif %}
        {% endfor %}

**Comment by did** [comment]
In your site source (Wagon), is your "news" page translated in all the locales, I mean, do you have a version of this page for each locale (news.fr.liquid, news.en.liquid and so on).
Besides, could you check that it's not defined as a templatized page?
Perhaps, you should post the code of your page.
thanks!

**Comment by CedricLor** [comment]
Hi @did 

The news page is translated in all the locales.

It is not defined as a templatized page.

Here is my header for news.liquid:
---
title: News
listed: true
published: true
position: 1
handle: news_index
slug: news
---

Would this be related to the fact that the page name is in plural (as news is always plural in English)? Convention over configuration... This is a Rails backend...

**Comment by CedricLor** [comment]
@did, when you say, templatized, do you mean, is it defined as content_type_template?

If so, no, it is not a content type template.

But it is used to list a content_type called news, which are, individually, displayed in a news/content_type_template.liquid file.

**Comment by did** [comment]
this commit (https://github.com/locomotivecms/steam/commit/dc2a571fe4180dad7d44ec43f0554a20ca2c65dc) should fix that issue!
