### ISSUE TITLE
Wagon does not recognize command "relationship"

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#274]
Documentation (https://locomotive-v3.readme.io/v1.0/docs/relate-two-content-types#belongs-to-the-book-belongs-to-the-author) says:
> You could also have used the Wagon relationship generator:
> 
>     bundle exec wagon relationship books belongs_to authors
> 
> This also generates the has_many relationship as explained in the next chapter.

If we try to use it we get error message *Could not find command "relationship".*:
```
$ bundle exec wagon relationship
Could not find command "relationship".
```

**Comment by did** [comment]
````
bundle exec wagon generate relationship ....
````

Typo in the doc :-(

**Comment by adam-pl** [comment]
Thank you for the info :)

**Comment by adam-pl** [comment]
It also doesn't work creation of content_type with belongs_to field type:
```
$ bundle exec wagon generate content_type books name:string category:belongs_to

home/adam/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.0.0.rc4/lib/locomotive/wagon/generators/content_type.rb:54:in `block (2 levels) in extract_fields': undefined method `singularize' for nil:NilClass (NoMethodError)
```
Is the reason I should use `bundle exec wagon generate relationship...` in second stage after `bundle exec wagon generate content_type books name:string` ?

**Comment by did** [comment]
yeah, don't add the definition of your category field when you first generate the content type.

**Comment by adam-pl** [comment]
Thx :)

**Comment by did** [comment]
you're welcome! Thanks for all your bug reports! btw, I'm almost done with the with_scope issue.

**Comment by adam-pl** [comment]
That's would be great - I cannot move my first CMS project forward because of `with_scope` issue.
I have one more similar issue connected with `with_scope`. 
I'll report it in a few minutes.
