### ISSUE TITLE
Resource invalid: handle is already taken

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/wagon#277]
With the latest version of the Wagon, the Engine and the Steam installed, when I do a:

    $ bundle exec push production

after having pushed many new sites (in the course of debugging) to the Engine, I get a:

      “Resource invalid: handle is already taken”

message, even though the corresponding “old” site has already been destroyed on the Engine.

When I go to the Engine’s interface, my site seems to be deployed.

I also get this message even thouhg my deploy.yml file contains the correct credentials to deploy to the Engine (for instance, when I want to make an update).

It might be related to this: https://github.com/locomotivecms/engine/issues/1087

It looks like former handles are cached somewhere where they do not get removed from when deploying a new site.

**Comment by CedricLor** [comment]
Correction: I do not have the latest version of the Wagon installed.

I have 2.0.0.rc4

with an amended steam in the Gemfile (locomotivecms_steam (1.0.0.rc6))

**Comment by CedricLor** [comment]
Issue closed, however, it might turn into a feature's request.

The "handle" to which Engine was referring was not the site handle, but a duplicate page handle.

The message returned by the console is not very explicit.

It would be nice if the message returned indicated at what line and while reading which file the issue arose.

**Comment by did** [comment]
@CedricLor Use the "-v" option to see exactly which resource failed.

**Comment by CedricLor** [comment]
Thanks @did. This will help!!!
