### ISSUE TITLE
"path_to books" returns nil

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#280]
REPRO

1. Create new project  - the same as descibed in issue #275
1. Edit `app/views/index.liquid`
1. Add following code inside the `content/main` block:

    ```
    <div class="row">
      <div class="col-sm-12">
        {% assign page_url = path_to 'books' %}
        {% if page_url %}
          <p>page_url: {{ page_url }}</p>
        {% else %}
          <p>error: page_url is nil!</p>
        {% endif %}
      </div>
    </div>
    ```
1. Launch the Wagon preview server
    ```
    bundle exec wagon serve  -v
    ```
1. Open internet browser with address `localhost:3333/`

WHATS WRONG
  - we get message  
    ```` 
    error: page_url is nil!
    ````
  - the same problem occurs on the Engine

IT SHOULD BE
  - we expect `page_url` is not nil
  - we expect `page_url` is equal to `localhost:3333/books`

Checked with `locomotivecms_wagon` 2.0.0.rc4 & `locomotivecms_steam` from master branch.   Gemfile is:

    source 'https://rubygems.org'
    gem 'locomotivecms_wagon', '~> 2.0.0.rc4'
    gem 'locomotivecms_steam', git: 'https://github.com/locomotivecms/steam.git'

    group :development do
      # Mac OS X
      gem 'rb-fsevent', '~> 0.9.1', require: 'rb-fsevent' if RUBY_PLATFORM.include?('darwin')
    
      # Unix
      gem 'therubyracer', require: 'v8', platforms: :ruby unless RUBY_PLATFORM.include?('darwin')
    
      gem 'rb-inotify', '~> 0.9', require: 'rb-inotify' if RUBY_PLATFORM.include?('linux')

      # Windows
      gem 'wdm', '~> 0.1.1', require: 'wdm' if RUBY_PLATFORM =~ /mswin|mingw/i
    end

    group :misc do
      # Add your extra gems here
      # gem 'susy', require: 'susy'
      # gem 'bourbon', require: 'bourbon'
    end

Documentation - https://locomotive-v3.readme.io/v1.0/docs/tags#path_to.

**Comment by adam-pl** [comment]
Similar problem is with using `link_to` even I define `handle` param in the view file.

**Comment by did** [comment]
hi @adam-pl,

I'm not sure that you're allowed to write ````{% assign page_url = path_to 'books' %}```` because path_to is liquid tag, not a drop or a filter. Try this instead:
````
{% capture page_url %}{% path_to books %}{% endcapture %}
````
Let me know if it worked.

**Comment by adam-pl** [comment]
It works :-)

Thank you for your explanation :)
