### ISSUE TITLE
"with_scope" doesn't work with "site.pages"

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#281]
REPRO

1. Create new project  - the same as descibed in issue #275
1. Edit `app/views/books.liquid` & add following line

    ````
    handle: books
    ````
1. Edit `app/views/index.liquid`
1. Add following code inside the `content/main` block:

    ```
    <div class="row">
        <div class="col-sm-6">
        {% with_scope listed: 'books' %}
          {% assign _page =  site.pages.first %}
        {% endwith_scope %}
        <p>Found page title: {{ _page.title }}</p>
      </div>
    </div>
    ```
1. Launch the Wagon preview server
    ```
    bundle exec wagon serve  -v
    ```
1. Open internet browser with address `localhost:3333/`

WHATS WRONG
  - we get message  
    ```` 
    Found page title: Home page
    ````

IT SHOULD BE
  - we expect message  
    ```` 
    Found page title: Books
    ````

Checked with `locomotivecms_wagon` 2.0.0.rc4 & `locomotivecms_steam` from master branch.   Gemfile is:

    source 'https://rubygems.org'
    gem 'locomotivecms_wagon', '~> 2.0.0.rc4'
    gem 'locomotivecms_steam', git: 'https://github.com/locomotivecms/steam.git'

    group :development do
      # Mac OS X
      gem 'rb-fsevent', '~> 0.9.1', require: 'rb-fsevent' if RUBY_PLATFORM.include?('darwin')
    
      # Unix
      gem 'therubyracer', require: 'v8', platforms: :ruby unless RUBY_PLATFORM.include?('darwin')
    
      gem 'rb-inotify', '~> 0.9', require: 'rb-inotify' if RUBY_PLATFORM.include?('linux')

      # Windows
      gem 'wdm', '~> 0.1.1', require: 'wdm' if RUBY_PLATFORM =~ /mswin|mingw/i
    end

    group :misc do
      # Add your extra gems here
      # gem 'susy', require: 'susy'
      # gem 'bourbon', require: 'bourbon'
    end

**Comment by adam-pl** [comment]
I do not know how to find specific page like 'books'.

**Comment by did** [comment]
hi @adam-pl, the following code worked for me:
````
{% with_scope handle: 'books' %}
  {% assign _page = site.pages.first %}
  {% endwith_scope %}
  <p>Page: {{ _page.title }}</p>
````

**Comment by adam-pl** [comment]
1. `{% with_scope handle: 'books' %}` doesn't work for me.

2. I've  updated locomotive gems:
```
Using locomotivecms-liquid 4.0.0
Using locomotivecms-solid 4.0.1
Using locomotivecms_coal 1.0.0.rc3
Using locomotivecms_common 0.0.5
Using locomotivecms_steam 1.0.0.rc7
Using locomotivecms_wagon 2.0.0.rc5
```
It still returns 'Page: Home page'.

**Comment by did** [comment]
@adam-pl I'm sorry but are you sure it's working with that code:
````liquid
<html>
<body>
  {% with_scope handle: 'books' %}
  {% assign _page = site.pages.first %}
  {% endwith_scope %}
  <p>Page: {{ _page.title }}</p>
</body>
</html>
````

**Comment by adam-pl** [comment]
1. It doesn't work with your code inserted in file `app/views/pages/index.liquid`.

2. To ensure it I replaced that code into:
    ```
    {% with_scope handle: 'books' %}
      {% assign _page_books = site.pages.first %}
    {% endwith_scope %}
    {% with_scope handle: 'home' %}
      {% assign _page_home = site.pages.first %}
    {% endwith_scope %}
    <p>Page(books): {{ _page_books.title }}</p>
    <p>Page(home): {{ _page_home.title }}</p>
    <p>Total Pages: {{ site.pages.size }}</p>
    ```

I expect to get two different titles.
Unfortunately I get `Home page` title twice.

The `index.liquid` files begins with:

    ---
    title: Home page
    published: true
    handle: home
    ---
The `books.liquid` file begins with:

    ---
    title: Books
    listed: true
    published: true
    handle: books
    ---
![zaznaczenie_056](https://cloud.githubusercontent.com/assets/2798350/11795106/3afb30d2-a2b5-11e5-9b6f-d55051eb1602.png)

**Comment by did** [comment]
@adam-pl I was able to reproduce this behaviour. thanks!
