### ISSUE TITLE
Missing translation for site wide meta keywords

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/wagon#283]
Hi,

I define site-wide meta keywords in my site.yml file as follows:

     meta_keywords:
       en: "English meta keywords"
       fr: "French meta keywords"

When displaying the pages and inspecting my head part of the rendered html, the keywords are rendered properly.

But if I look at my log file, I see 

       Missing translation 'French meta keywords' for the 'fr' locale

and 

       Missing translation 'English meta keywords' for the 'en' locale

depending on whether I browsed to the French or English version of the page.

From a practical point of view, this does not really bother me. Just the logs that are weird.

**Comment by did** [comment]
alright, that was caused by a wrong use of the ````site.meta_keywords```` statement.

````<meta name="keywords" content="{{ site.meta_keywords | escape | translate }} ```` **(no need to use the translate filter)**.

**Comment by CedricLor** [comment]
Thanks @did !!!
