### ISSUE TITLE
posted_at can't be blank while pushing to the Engine

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/wagon#285]
See a description of the issue in Coal https://github.com/locomotivecms/coal/issues/15

This occurs with version of Wagon 2.0.0.rc5 and Coal locomotivecms_coal (~> 1.0.0.rc3)

**Comment by did** [comment]
the posted_at attribute was not submitted to Engine. The problem was that the field was localized with the same value for all the locales in the yaml data file.
