### ISSUE TITLE
building image url for pinterest

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#286]
I would like to prepare anchor for sharing article with image on pinterest web site.

The problem is I need to build full url of given image instead of relative path that `theme_image_url` does.
Now I can do that in following way:
```
<a href="//pinterest.com/pin/create/button/?url={{ url }}&amp;media=http://{{ host }}{{ 'tree.jpg' | theme_image_url }}&amp;description=The tree" target="_blank">Share it on Pinterest</a>
```

I do not like using `http://{{ host }}`.
Is there any filter that converts relative image path to full url?

**Comment by did** [comment]
@adam-pl theme_image_url can be confusing because it may return a full url if you use a CDN to serve your assets OR if you use AWS S3. 
Perhaps, a "absolute_url" liquid filter in Steam would handle all the different cases.
````liquid
 {{ 'tree.jpg' | theme_image_url | absolute_url }}
````

**Comment by adam-pl** [comment]
@did , I do not use [cmer/rails-assets-cdn](https://github.com/cmer/rails-assets-cdn) gem.
I would like to get full url on the Wagon & the Engine installed locally first.

I rewrote my code to:
```
<a href="//pinterest.com/pin/create/button/?url={{ url }}&amp;media={{ 'tree.jpg' | theme_image_url | absolute_url }}&amp;description=The tree" target="_blank">Share it on Pinterest</a>
```

So I used `{{ 'tree.jpg' | theme_image_url | absolute_url }}`.  
It renders as:
```
<a href="//pinterest.com/pin/create/button/?url=http://localhost:3333/about&amp;media=/images/tree.jpg&amp;description=The tree" target="_blank">Share it on Pinterest</a>
```

The `media` param doesn't have full url.  
I get `media=/images/tree.jpg` instead of `media=http://localhost:3333/images/tree.jpg`

`absolute_url` method from file `lib/locomotive/steam/liquid/filters/base.rb` is:

    ```
      def absolute_url(url)
        url.starts_with?('/') ? url : "/#{url}"
      end
    ```
It only adds '/' char to the url param.

**Comment by did** [comment]
I'm sorry @adam-pl , I wrote ````absolute_url```` but I didn't remember it existed for real :-(
I'm going to find something else. I keep you posted.

**Comment by adam-pl** [comment]
Grat job @did - it works now :)
