### ISSUE TITLE
Site works on production, but loads without styles on local machine.

### ISSUE THREAD

**Issue by craft37** [locomotivecms/wagon#288]
So, site works on production well after deploy from local machine with 'bundle exec wagon deploy production'.
But local copy of website runned with 'bundle exec wagon serve' loads without styles, despite styles putted in right way like in themplate examples, in public/stylesheets and connected with this code:

{{ 'bootstrap.min.css' | stylesheet_tag }}
{{ 'style.css' | stylesheet_tag }}

What the reason of this may be? How to see site properly on local machine too?
Thanks.

**Comment by did** [comment]
@craft37 I'm sorry, not sure to understand. 

You created your site with Wagon locally and you deployed it without knowing if the css would work or not, right? 

What do you see in the logs/wagon.log file? Besides, what does your browser console tell you (any errors?)?

thanks!

**Comment by craft37** [comment]
@did Yes, I created site through remote wagon, than copied site to local machine.
And meh, forgot to install imagemagick :)
Thank you.

**Comment by did** [comment]
@craft37 I'm sorry, does it work now?

**Comment by craft37** [comment]
@did Yes, wagon work now, imagemagick was needed.

**Comment by did** [comment]
@craft37 Do we need to update the documentation?

**Comment by craft37** [comment]
@did Surely it would be better, as on website docs, as on Developer section just in admin also. Thank you.
