### ISSUE TITLE
Newest wagon doesn't push "public/samples" directory

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#290]
Newest Wagon does not push `public/samples` directory to the Engine.

If we preview page with the Wagon every image included in `public/samples` directory is visible.

If we push our site to the Engine, images from `public/samples` are not visible because "public/samples" directory doesn't exist in the Engine' site.

**Comment by adam-pl** [comment]
I've investingated my issue.

The Engine stores themes in `public/sites/xxxxxxxxxxxxx/assets` directory.

Images used in snippet files are not pushed to the Engine. They are missed.

REPRO

1. Create new project with bootstrap template
1. Copy image files into:

    ```
    public/images/staff/staff1.jpg
    public/samples/slider/slide1.jpg
    ```
1. Insert code into file `app/views/pages/layouts/default.liquid`:

  ```
      <div class="container">
        {% include picture_extra %}
      </div>
  ```
1. Create snippet `picture_extra`

  ```
  <div class="row">
    <h2>A. Image from "public/samples/" directory</h2>
    <h3>1. "/samples/slider/slide1.jpg"</h3>
    <img src="{{ '/samples/slider/slide1.jpg' }}" alt="image not scaled" />
  
    <h3>2. '/samples/slider/slide1.jpg' | resize: '192x80#'</h3>
    <img src="{{ '/samples/slider/slide1.jpg' | resize: '192x80#' }}" alt="image scaled to 192x80" width="192" height="80" />
  </div>

  <div class="row">
    <h2>B. Image from "public/images/" directory, not scaled</h2>
    <h3>1. 'staff/staff1.jpg'</h3>
    <img src="{{ 'staff/staff1.jpg' }}" alt="image not scaled" />
    <h3>2. 'staff/staff1.jpg' | absolute_url</h3>
    <img src="{{ 'staff/staff1.jpg' | absolute_url }}" alt="image not scaled" />
    <h3>3. '/images/staff/staff1.jpg'</h3>
    <img src="{{ '/images/staff/staff1.jpg' }}" alt="image not scaled" />
  </div>

  <div class="row">  
    <h2>C. Image from "public/images/" directory, scaled (100x100)</h2>
    <h3>1. 'staff/staff1.jpg' | resize: '100x100#'</h3>
    <img src="{{ 'staff/staff1.jpg' | resize: '100x100#' }}" alt="image scaled to 100x100" width="100" height="100" />
    <h3>2. '/images/staff/staff1.jpg' | resize: '100x100#'</h3>
    <img src="{{ '/images/staff/staff1.jpg' | resize: '100x100#' }}" alt="image scaled to 100x100" width="100" height="100" />
  </div>
  ```

THE WAGON
1. Open index page 

WHAT'S WRONG
1. 3 of 7 image files are not visible:
  - B.1. 'staff/staff1.jpg'
  - B.2. 'staff/staff1.jpg' | absolute_url
  - C.1. 'staff/staff1.jpg' | resize: '100x100#'

It seems that the Wagon recognizes only paths with included '/images/' prefix inside snippets.

THE ENGINE
1. Push new project to the Engine (tested on locally installation)
1. Open index page

WHAT'S WRONG
1. 7 of 7 images files are not visible!

**Comment by did** [comment]
@adam-pl that should be clarified in the documentation but here is how it works:

- if you put your images inside public/images, they are considered as theme assets and so you need to use the appropriate liquid tag: https://locomotive-v3.readme.io/docs/filters#theme_image_url
- if you put your images inside public/samples/**, they will deployed to Engine only if you reference them in your templates or content entries. That being said, it seems that it doesn't apply to snippet. So that's a bug :-)
