### ISSUE TITLE
Change name of page from admin management on web

### ISSUE THREAD

**Issue by vinhcp** [locomotivecms/wagon#293]
Hi @did 

**Context**: My development pages have been initiated from the pages that I synced from production, after then I want to sync some changes on production and deploy to development.
1. On production, I have a page that's named 'My Page' and when I sync it in the first time, I see the file 'my-page.liquid'. After then, I change the page name to 'My Custom Page', and I also see the 'my-custom-page.liquid' after syncing. But, when I deploy them to development, wagon doesn't deploy 'my-custom-page.liquid'. How can I deploy the change in this case with creating a new page 'My Custom Page' on development. That really makes me confuse.
2. Also there is an error 'Resource invalid: handle is already taken' when deploying to deployment. This is the content of 2 files
   ...... my-page.liquid .....
   _handle: my_handle
   position: 1_
   ...... my-custom-page.liquid .....
   _handle: my_handle
   position: 1_
   But I remove the line 'handle' from my-custom-page.liquid, I deploy success but I cannot the change when I view pages in admin management.
3. The last thing, I changed editable text of page 'example.liquid' on production and synced that page successfully, but I can't see the changes when I deploy that page to development. Please clarify me this one?

Thank you.

**Comment by did** [comment]
the Wagon sync has been rewritten: https://doc.locomotivecms.com/v4.0/docs/synchronize-content
