### ISSUE TITLE
pushing many site domains via command line

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#297]
Let's say I have defined 100 domains for my site in `config/site.yml` file:

    domains: [www.domain1.net, www.domain2.net, www.domain3.net, www.domain4.net, ... , www.domain100.net]

I would like to push defined domains to the Engine. So I try to do it by following command:

    bundle exec wagon push production -v -d -r site

I get following results:

    Pushing Site
    persisting Domain1.net [done]

    Your site has been deployed.

But if I check domains settings in the Engine I'll get no definitions. 
I must add it manually. It's not comfortable for adding 100 domains.

Is there any way to push domains by command line with the Wagon?

**Comment by did** [comment]
@adam-pl domains are never pushed. I think pushing domains are too dangerous. I should put a note on the config/site.yml file specifying that domains won't never pushed (in case you need them in your liquid templates in Wagon).

Back to your initial request, I'd use Coal (https://github.com/locomotivecms/coal). Here is the ruby script I'd write (not tested).

````ruby
require 'locomotive/coal'

client = Locomotive::Coal::Client.new('http://<YOUR ENGINE>', { email: <EMAIL>, api_key: <API KEY> })

site_client = client.scope_by('<YOUR SITE HANDLE>')

site_client.current_site.update(domains: <ARRAY OF DOMAINS>)
````

**Comment by adam-pl** [comment]
@did, that's good solution.

I've never used the Coal yet. I have to check it soon.
Thank you.
