### ISSUE TITLE
Snippet created with subdirectory is not loaded

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#300]
##### REPRO
1. Create new project:
   
   ```
   wagon init Library -t bootstrap
   ```
2. Create template `books` with using subdirectory `boxes`:
   
   ```
   bundle exec wagon generate snippet boxes/books
   ```
3. Include created snippet into file `app/views/pages/index.liquid`
   
   ```
   {% include boxes/books %}
   ```
4. Run the Wagon and open main page in your favorite browser
##### WHAT"S WRONG
1. We'll get following error:
   
   ```
   Liquid error: Snippet with slug 'boxes/books' was not found
   ```

**Comment by did** [comment]
@adam-pl, that's a new feature :-)

**Comment by bekicot** [comment]
@did Sounds cool, On which version ?

**Comment by sweetymehta** [comment]
@did found same issue, how can I avail this feature?

**Comment by did** [comment]
we want to keep the code in charge of loading the snippets as simplest as possible so we're not going to implement subdirectory mechanism for the snippets :-(
