### ISSUE TITLE
Can't create file log/server.log

### ISSUE THREAD

**Issue by renatonlima** [locomotivecms/wagon#301]
Hello,

Using wagon 2.0.1, when I try run:

```
$bundle exec wagon serve
```

I have this error:

```
No such file or directory @ rb_sysopen - /home/renato/projects/websites/wagons/test/log/server.log
```

If I create this file manually, it's works fine! This file should be created automatically, right?

**Comment by dustb0wl** [comment]
This was resolved in 2.1.0.rc3.  If you upgrade to 2.1.0.rc3 or above, it will create the file if not present.
