### ISSUE TITLE
Long time request answer of page while using page.next and page.next for content_entry with 500 records

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#302]
REPRO
1. I have defined ~ 500 records in the `posts.yml` file that defines entries for `posts` content_entry.
2. My view contains navigation section for creating anchor for the next & previous posts. So I use `post.next` & `post.previous` attribute.
3. If I try to load any post page in a browser I'll get long time request answer. It takes about **10 seconds** on my local machine.
4. If I remove the navigation section then post page loads very quick (~400 ms)

WHAT'S WRONG
1. **10 seconds** is too much.

HOW IT SHOULD BE
1. **1 second** would be great

INFO

The problem occurs only in the Wagon.

Is there any possibility to speed up loading page with big amount of content_entries while using `post.next` & `post.previous` attributes?

**Comment by did** [comment]
Wagon doesn't use a database so we hit a wall in terms of performance when we get too many data. We plan to keep it like this for now. When we'll make the move to Posgresql one day, perhaps we'd use sqlite to manage local content.
