### ISSUE TITLE
Getting error when deleting resource content_type

### ISSUE THREAD

**Issue by iuriandreazza** [locomotivecms/wagon#306]
Hello, 

I was trying to delete some resources (a content_type) but when I run the command as described in the docs (https://locomotive-v3.readme.io/v3.0/docs/delete-resources)

`➜  reever_research_development bundle exec wagon delete staging content_type reever/BlogCategories

Are you sure? [yes, no] yes

/Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/concerns/api_concern.rb:16:in `api_site_client': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/delete_command.rb:73:in `client'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/delete_command.rb:49:in `delete_single'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/delete_command.rb:28:in `delete'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/delete_command.rb:20:in `delete'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:120:in `delete'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:367:in `delete'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/bin/wagon:23:in `load'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/bin/wagon:23:in `<main>'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/iuriandreazza/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by did** [comment]
@iuriandreazza. what's the slug of your content type? If it's **blog_categories**, the command would be:
````
bundle exec wagon delete staging content_type blog_categories
````
