### ISSUE TITLE
Foundation5 template is not working

### ISSUE THREAD

**Issue by openscript** [locomotivecms/wagon#308]
I ran into the following problem, when I initialized a new wagon with the Foundation5 template:

![image](https://cloud.githubusercontent.com/assets/1105080/16045897/c60de244-324a-11e6-88c5-34e44f050083.png)

Steps to reproduce:

1. gem install bundler
1. gem install locomotivecms_wagon
1. wagon init test -t foundation5
  * Do you prefer HAML templates? y
  * Do you prefer SCSS stylesheets? y
1. cd ./test
1. bundle install
1. bundle exec wagon serve
1. open http://0.0.0.0:3333

Thank you for any help.

**Comment by did** [comment]
@openscript renaming the .css.scss files into .scss (basically, dropping the .css) fixes your issue. thanks!
