### ISSUE TITLE
Upgrade foundation5 template to foundation6

### ISSUE THREAD

**Issue by openscript** [locomotivecms/wagon#309]
Since a few months foundation6 is out. They also upgraded the rails gem of it. What are the steps to get the new foundation to work with locomotive?

**Comment by did** [comment]
hey @openscript, we could embed it in Wagon like we did for foundation5. Check those links:
- https://github.com/locomotivecms/wagon/blob/master/lib/locomotive/wagon/generators/site/foundation5.rb
- https://github.com/locomotivecms/wagon/tree/master/generators/foundation5
Send me a PR if you've got time. Thanks for your help!

**Comment by did** [comment]
We don't integrate Foundation or Bootstrap anymore in Wagon v3. The alternative is to use Webpack to install any HTML/CSS/JS framework (https://doc.locomotivecms.com/v4.0/docs/manage-js-and-css-with-webpack).
