### ISSUE TITLE
Hide content type in back office

### ISSUE THREAD

**Issue by sweetymehta** [locomotivecms/wagon#310]
@did  As I tried display_settings properties in yaml, but did not work. I want to hide some content types in back office based on some condition. Any help?

**Comment by adam-pl** [comment]
It works for me.

I wanted to hide categories model from Editors. I have following definition in `app/content_type/categories.yml` file:
```
display_settings:
  hidden: true
```

Note that categories is hidden only for Editors.

**Comment by sweetymehta** [comment]
Thanks @adam-pl, It is working for membership as an author.
