### ISSUE TITLE
Cannot deploy single content_entry with the Wagon

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#311]
**REPRO**
1. Create new project & two models: categories, groups
2. Deploy all to the Engine
3. Edit `data/categories.yml` and do some changes (on the Wagon site)
4. Try to deploy only `categories.yml` to the Engine like that:

```
bundle exec wagon push my_site -v -d -r content_entries -f categories
```

**WHAT'S WRONG**
1. The Wagon pushes all content entries: `categories` & `groups`

**HOW IT SHOULD BE**
1. The Wagon should push only `categories` content entry.

**Comment by did** [comment]
That's because Categories and Groups are related through a belongs_to/has_many or a many_to_many relationship.
