### ISSUE TITLE
How to fetch conent type entries in custom tag

### ISSUE THREAD

**Issue by danielmyasnikov** [locomotivecms/wagon#314]
**Issue fetching content type entries in wagon custom tag**

I have a custom liquid tag, that fetches content type entries nicely when it runs with `locomotive_cms`

Here is the tag: https://gist.github.com/danielmyasnikov/13c2a2259ca79e42da1521742e30f464

However when the tag is executed in the locomotivecms_wagon environment (reads from file_system), the gem fails to find content type entries.

So, the question is how does one fetch content type entries from the file and parse it nicely with liquid tags, so later I can execute different operation such as `pagination`, `scoping`, etc etc

My assumption was, I can do something like:
1. Fetching content_types
```
Locomotive::Wagon::Liquid::Drops::ProxyCollection.new('crews')
```
2. Fetching content
```
mp = Locomotive::Mounter::MountingPoint.new
mp.path = '/Users/myusername/src/wagon-folder'

runner = Locomotive::Mounter::Reader::FileSystem::Runner.new(:file_system)
runner.path = '/Users/myusername/src/wagon-folder'

ctr = Locomotive::Mounter::Reader::FileSystem::ContentTypesReader.new(runner)
ctr.read
content_type = ctr.items['crews']
ctr.items['crews'].class.inspect # "Locomotive::Mounter::Models::ContentType"

ctr.items['crews'].entries # => nil
```
Which means that `@collection` will empty and all further operation will fail.

That would be awesome if you can provide the info on how to get content_entries in tags. Thanks

Version of locomotive: `2.5.5`
Version of wagon: `1.5.8`

**Comment by danielmyasnikov** [comment]
@manuchap, @mariovisic you guys might know the answer, please :)

**Comment by mariovisic** [comment]
@danielmyasnikov sorry, I haven't worked on the project for years. Good luck though :)

**Comment by did** [comment]
@danielmyasnikov. All the code about fetching content entries is now located in the Steam gem (https://github.com/locomotivecms/steam). Some specs which will give you some insights: https://github.com/locomotivecms/steam/blob/master/spec/integration/repositories/content_entry_repository_spec.rb.
