### ISSUE TITLE
Duplicate handle error on multilingual sites

### ISSUE THREAD

**Issue by banditrider** [locomotivecms/wagon#315]
There is an unexpected error on multilingual sites on wagon versions later tan 2.0.1:
`The local and the remote (folder/page_slug) versions of that page have the same handle but they are not in the same folder.`

As discussed on Gitter: 
- The error is caused by the fact that multilingual versions of the same page can have different slugs. 
- A folder in the same directory is typically named after the slug of a corresponding page. If that page has different slugs for different languages (which is reasonable), the folder name is also different for distinct languages, thus wagon currently throws an error since it currently requires that the page handle needs to be unique and in the same *translated* folder name.

Thus, quote did: **We should only check if the handle is associated to the same page path ONLY in the default locale.**

My suggestion would be to also add any naming restriction to the i18n doc, so developers are aware of those restrictions.

**Comment by did** [comment]
@banditrider it would be awesome if you could give a shot to my fix. Also, with this fix, we wouldn't have to modify the documentation about some naming restriction. Am I right?
thanks for the very clear bug explanation btw 👍

**Comment by banditrider** [comment]
@did I'd say that does it, thank you! Deploying with this commit on our site works as it should

Regarding the naming restriction: I don't know how the folder structure is implemented, but if a folder is guaranteed to have the same name as the corresponding page slug in the default locale, then no additional explanation is required with this fix.
