### ISSUE TITLE
delete command throws error when used with -v flag

### ISSUE THREAD

**Issue by banditrider** [locomotivecms/wagon#317]
Using a delete command such as `wagon delete prod content_type some_content_type -v` throws an unexpected error when used with the `-v` flag:

    Unable to read the config/deploy.yml file (No such file or directory @ rb_sysopen - -v/config/deploy.yml)

(Of course the deploy.yml both exists and is filled correctly)

The _delete_ command works as expected once the `-v` flag is removed.

**Comment by did** [comment]
well, there is no ```-v``` option for that command.

**Comment by banditrider** [comment]
In this case, shouldn't then be some kind of invalid flag/option error
rather than a misleading error message about deploy.yml.
I'd find it quite intuitive that the -v flag could be available on all
commands, so maybe a more helpful error message could safe some ppl some
trouble.
