### ISSUE TITLE
Incorrectly caught error on interrupted/bad connection while deploying

### ISSUE THREAD

**Issue by banditrider** [locomotivecms/wagon#318]
A bad connection can lead to `undefined method 'body' for #<Faraday::TimeoutError>` during deployment (wagon 2.2.0-rc1). 

As discussed on Gitter, a better way of catching and handling this error makes sense. I'd expect a specific error message (e.g. Connection to remote server timed out - please check your internet connection) and Did mentioned the introduction of a retry mechanism.

**Comment by did** [comment]
found that. http://www.rubydoc.info/github/lostisland/faraday/Faraday/Request/Retry

**Comment by greyskin** [comment]
I'm getting this same error but my internet connection is fine. The error always happens at a different stage of deployment...

**Comment by did** [comment]
related to #249

**Comment by manuchap** [comment]
Weird workaround/trick I often use:
I have a poor connection (400Ko/s max). If I want to accelerate a flux (deploy, clone, nmp...) I just launch a random youtube video and everything gets faster. Go figure this one out...
@banditrider Try it out and tell me if it works for you too.

**Comment by greyskin** [comment]
@manuchap - amazing! I am definitely going to give this a go!

**Comment by did** [comment]
PR merged in Coal so it will available soon in Wagon
