### ISSUE TITLE
javascript assets are minified when pulling

### ISSUE THREAD

**Issue by bpatram** [locomotivecms/wagon#320]
When running `wagon pull [site env]` it will pull down a minified version of your javascript files instead of the original file that was uploaded (via `wagon push` or `wagon deploy`). 

This gets frustrating when you pull your site down and it overwrites your javascript files with a minified version.

**Comment by did** [comment]
The engine only stores the minified versions of the assets. So ```wagon pull``` is more like a site backup. Use ```wagon sync``` to only fetch the content of editable elements, content entries and translations.
