### ISSUE TITLE
wagon clone won't work

### ISSUE THREAD

**Issue by nik736** [locomotivecms/wagon#321]
Hi guys,

I've installed the engine on my own server and everything works fine apart from the wagon clone command, which returns the following:

> Nik-MacPro:testee nik$ wagon clone xxx http://url -h xxx-4797 -e email -a xxxx -v
>       create  xxx
>       create  xxx/Gemfile
>       create  xxx/Guardfile
>       create  xxx/app/content_types
>       create  xxx/app/views/pages
>       create  xxx/app/views/snippets
>       create  xxx/config/deploy.yml
>       create  xxx/data
>       create  xxx/public/fonts
>       create  xxx/public/images
>       create  xxx/public/javascripts
>       create  xxx/public/samples
>       create  xxx/public/stylesheets
> 
> # Error description:
> undefined method `join' for "422":String
> Did you mean?  JSON
> 
> # Backtrace:
> 
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/concerns/request.rb:30:in `rescue in do_request'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/concerns/request.rb:23:in `do_request'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/concerns/request.rb:7:in `get'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/current_site.rb:9:in `get'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_command.rb:41:in `_pull'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_command.rb:30:in `pull'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_command.rb:24:in `pull'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:85:in `pull'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/clone_command.rb:30:in `pull_site'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/clone_command.rb:14:in `clone'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/clone_command.rb:6:in `clone'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:109:in `clone'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:236:in `backup'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/bin/wagon:23:in `load'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/bin/wagon:23:in `<main>'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
> 	/Users/nik/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
> 

I also tried the command from a linux machine and get the same error, so maybe something is wrong with my engine?

Thanks for any help!

**Comment by nik736** [comment]
I just tested it on locomotive.works and there everything works alright. So I guess it's a problem with my installed engine, hm...

**Comment by did** [comment]
hey @nik736, on Station, we're using the last RC of Engine.

**Comment by did** [comment]
Station = locomotive.works :-)

**Comment by nik736** [comment]
Thanks for the answer.

I just updated my engine to 3.2.0.rc2 but it's still the same error. Any idea what could be wrong?

**Comment by did** [comment]
@nik736 what do your server logs tell you about that?

**Comment by nik736** [comment]
Hi @did:

> I, [2016-09-26T17:47:36.586264 #28146]  INFO -- : Started POST "/locomotive/api/v3/tokens.json" for 95.208.172.10 at 2016-09-26 17:47:36 +0200
> I, [2016-09-26T17:47:36.586550 #28146]  INFO -- : [LocomotiveCMS] [fetch site] host = xxxxxxxxx.de / site_handle = nil / locale = :en
> D, [2016-09-26T17:47:36.587857 #28146] DEBUG -- : MONGODB | localhost:27017 | cms_production.find | STARTED | {"find"=>"locomotive_sites", "filter"=>{"domains"=>{"$in"=>["xxxxxxxxx.de.de"]}}, "limit"=>1, "singleBatch"=>true}
> D, [2016-09-26T17:47:36.588566 #28146] DEBUG -- : MONGODB | localhost:27017 | cms_production.find | SUCCEEDED | 0.000595466s
> D, [2016-09-26T17:47:36.589825 #28146] DEBUG -- : MONGODB | localhost:27017 | cms_production.find | STARTED | {"find"=>"locomotive_sites", "filter"=>{"domains"=>{"$in"=>["xxxxxxxxx.de.de"]}}}
> D, [2016-09-26T17:47:36.590133 #28146] DEBUG -- : MONGODB | localhost:27017 | cms_production.find | SUCCEEDED | 0.000231603s
> D, [2016-09-26T17:47:36.590599 #28146] DEBUG -- : MONGODB | localhost:27017 | cms_production.count | STARTED | {"count"=>"locomotive_accounts", "query"=>{}}
> D, [2016-09-26T17:47:36.591167 #28146] DEBUG -- : MONGODB | localhost:27017 | cms_production.count | SUCCEEDED | 0.00038348399999999996s
> I, [2016-09-26T17:47:36.593024 #28146]  INFO -- : Processing by Locomotive::ErrorsController#no_site as JSON
> I, [2016-09-26T17:47:36.593486 #28146]  INFO -- :   Parameters: {"api_key"=>"84bcc0420b96165a116f23f44794ea5c43e3d641", "email"=>"email"}
> W, [2016-09-26T17:47:36.597618 #28146]  WARN -- : Can't verify CSRF token authenticity
> I, [2016-09-26T17:47:36.598465 #28146]  INFO -- : Completed 422 Unprocessable Entity in 5ms
> F, [2016-09-26T17:47:36.602210 #28146] FATAL -- : 
> ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
>   actionpack (4.2.7.1) lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'
>   actionpack (4.2.7.1) lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request'
>   devise (3.5.10) lib/devise/controllers/helpers.rb:257:in `handle_unverified_request'
>   actionpack (4.2.7.1) lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:164:in `block in halting'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:504:in `block in call'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:504:in `each'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:504:in `call'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
>   actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
>   actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
>   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
>   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
>   activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
>   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
>   actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
>   actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
>   actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
>   actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
>   actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
>   actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
>   locomotivecms (3.2.0.rc2) lib/locomotive/middlewares/site.rb:60:in `handle_no_account_or_site'
>   locomotivecms (3.2.0.rc2) lib/locomotive/middlewares/site.rb:28:in `rescue in call'
>   locomotivecms (3.2.0.rc2) lib/locomotive/middlewares/site.rb:25:in `call'
>   dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
>   warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
>   warden (1.2.6) lib/warden/manager.rb:34:in `catch'
>   warden (1.2.6) lib/warden/manager.rb:34:in `call'
>   rack (1.6.4) lib/rack/etag.rb:24:in `call'
>   rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
>   rack (1.6.4) lib/rack/head.rb:13:in `call'
>   actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
>   actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
>   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
>   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
>   actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
>   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
>   activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
>   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
>   actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
>   actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
>   actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>   railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
>   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
>   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
>   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
>   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
>   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
>   actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
>   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
>   locomotivecms (3.2.0.rc2) lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
>   dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
>   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
>   activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
>   railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
>   railties (4.2.7.1) lib/rails/application.rb:165:in `call'
>   puma (3.6.0) lib/puma/configuration.rb:225:in `call'
>   puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
>   puma (3.6.0) lib/puma/server.rb:415:in `process_client'
>   puma (3.6.0) lib/puma/server.rb:275:in `block in run'
>   puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
> 
>

**Comment by did** [comment]
alright, so the core issue is that your credentials are wrong. It's not clear in Wagon because you might not have the last version of Wagon.

**Comment by nik736** [comment]
Thats weird, I just copy pasted the wagon clone line from the backend. I also just double checked the API key and generated a new one. Changes nothing, still the same error.

I tried several wagon versions, the error stays the same, currently I am on:

> Niklass-MacPro:asd nik$ wagon version
> 2.2.0.rc2

**Comment by did** [comment]
@nik736 from your logs, it seems that Engine can't find your site.

**Comment by nik736** [comment]
I don't know why but it works now. I reinstalled the engine from scratch and it works now even though I made nothing different compared to the first time. Thanks for your help anyways. :-)
