### ISSUE TITLE
Duplicate page when syncing with production

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/wagon#324]
I have a page that corresponds to a content type(used as index) and that page has a different `slug` and file name, so when i sync the page file gets duplicated. The synced page file will then have the name of the slug.
EDIT: I just realized it also happens on a folder level. I got a duplicate of the folder with the content_type_template which took the name of the slug of the index.

**Comment by manuchap** [comment]
+1 sync converts hyphens (-) to underscores (_) in paths.
I don't use - in folder or filenames anymore

**Comment by marthings** [comment]
Same problem here:/ i find IT weird that i get a template for layouts when its just a folder. Also having the same issues above. The sync / wagon cli is one of the killer features for me but its just annoying to sync at the moment since i have to manuelly remove stuff "generated wrong"

**Comment by did** [comment]
The [new sync command](https://doc.locomotivecms.com/v4.0/docs/synchronize-content) would prevent this issue in my opinion.
