### ISSUE TITLE
Tag releases or add changelog?

### ISSUE THREAD

**Issue by bpatram** [locomotivecms/wagon#326]
Would it be possible to tag releases on github along with release notes or in the very least a CHANGELOG.md file to track changes per version. 

It seems as though there are only two releases listed currently which gives off the impression this project hasn't had a release since 2013!!

It would be very helpful to know what changes occurred between releases when updating

**Comment by did** [comment]
hi @bpatram, sure! It works pretty well with Engine when I release a new version. I've to point the differences between the 2 Rakefile.
