### ISSUE TITLE
Wagon clone issue - SSL_connect returned=1 errno=0 state=error: certificate verify failed

### ISSUE THREAD

**Issue by anneminford** [locomotivecms/wagon#327]
Hi, I am trying to set up locomotivecms on a windows 10 machine but I am getting this error when I try to clone a site: -

# Error description:
SSL_connect returned=1 errno=0 state=error: certificate verify failed

I have deployed the fix described here http://guides.rubygems.org/ssl-certificate-update/, but I am still getting the issue:

Any ideas?

**Comment by jlovick** [comment]
are you by chance trying to clone a https site that is using a wildcard ssl certificate?
I am getting this error in this situation
