### ISSUE TITLE
Assets persisting regex is false on site metafields images

### ISSUE THREAD

**Issue by merqlove** [locomotivecms/wagon#329]
https://github.com/locomotivecms/wagon/blob/master/lib/locomotive/wagon/decorators/concerns/persist_assets_concern.rb#L10

Illustration with spec & fix:

https://github.com/merqlove/wagon/commit/e67534f9087fcea4f84f30ff98c5243ce19fec34
https://github.com/merqlove/wagon/commit/6078a0b5cf49522b4d93f61766ce887ddd6a7aa5

**Comment by did** [comment]
thanks! couldn't believe that I noticed this issue just today :-(
