### ISSUE TITLE
Silent Wagon on Heroku App

### ISSUE THREAD

**Issue by mguastafierro** [locomotivecms/wagon#331]
I did deploy to Heroku. The Log is okay but when I connect to https://appname.herokuapp.com/locomotive/ I do not see anything... Why?

**Comment by manuchap** [comment]
Because your app is located at https://nameofyourapp.herokuapp.com

**Comment by mguastafierro** [comment]
No. On https://myapp.herokuapp.com there is nothing...

**Comment by manuchap** [comment]
Did you use the one click install or the manual method?
(I believe your app isn't called myapp btw is it?)

**Comment by mguastafierro** [comment]
1 click install with "Deploy to Heroku" Button on https://locomotive-v3.readme.io/docs/heroku...
