### ISSUE TITLE
Recurring issue when deploying content_types and/or content_entries

### ISSUE THREAD

**Issue by AzoRAI** [locomotivecms/wagon#332]
When pushing content_types or content_entries, this error crops up when something is not exactly as it should be.  Usually it takes several hours of going through every line of the file to figure out what the errors stems from.

Circumstances I've encountered this error so far:
- Malformed file, wrong indents, etc
- Invalid slug formats
- Relationships unable to be found  (Most common issue)

I'm sure the source of this issue is some yml to hash parsing somewhere. If you can narrow that down I can do a few things to try and produce more specific logging.  

It is incredibly frustrating when the error could literally be anywhere.  There have been times when having gone down the checklist of known scenarios and the error still persists.

    undefined method `join' for nil:NilClass

# Error description:
undefined method `join' for nil:NilClass

# Backtrace:

	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/error.rb:72:in `block in build_message'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/error.rb:66:in `map'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/error.rb:66:in `build_message'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/error.rb:12:in `initialize'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/error.rb:30:in `new'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/error.rb:30:in `from_response'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/concerns/request.rb:15:in `put'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/resources/base.rb:35:in `update_with_locale'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:42:in `persist'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:34:in `block in _push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:12:in `block in _push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:10:in `each'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:10:in `_push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/activesupport-4.2.6/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:50:in `instrument'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:55:in `block in _push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:84:in `block in each_resource'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:77:in `each'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:77:in `each_resource'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:54:in `_push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:41:in `push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:73:in `push'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:318:in `deploy'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/bin/wagon:23:in `load'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/bin/wagon:23:in `<main>'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/bin/ruby_executable_hooks:15:in `eval'
	/Users/joshuat/.rvm/gems/ruby-2.2.0@wagon/bin/ruby_executable_hooks:15:in `<main>'

**Comment by did** [comment]
hi @JoshuaTyree, I understand your frustration. Have you tried the very last version of Wagon? I completely redesigned the error page + the logic behind it so that it's easier now to know what happened. 
If it's incomplete for you, no pb, let's improve this case by case. I leave this issue open. Just post your cases here. thanks!

**Comment by DonKoko** [comment]
@JoshuaTyree I completely agree. This can be very frustrating. I am also willing to jump into improving this. You should try the new wagon version, it's way better in displaying errors.
