### ISSUE TITLE
How to create custom liquid tag

### ISSUE THREAD

**Issue by vmatekole** [locomotivecms/wagon#333]
We’re using Locomotive to develop our new blog, and so far have enjoyed working with it. We want to pull in a common header/footer for the blog and thought a custom liquid function maybe suitable. However, there seems to be no up to date methods to do this —https://github.com/locomotivecms/wagon/issues/77

Can you help?

**Comment by did** [comment]
thanks @vmatekole. The problem with custom liquid tags is that you can't use them in our hosting platform. 
If others read that issue, the right way is to tell us what kind of filters/tags you miss in Wagon.
