### ISSUE TITLE
Feature request: Adding asset_host_url as an option in Wagon configuration

### ISSUE THREAD

**Issue by siddhantbhardwaj** [locomotivecms/wagon#334]
It'd be very nice to be able to set the asset host url up on a site-by-site basis. This can be useful from SEO standpoint too.

**Comment by interhive** [comment]
I was able to get this working without making code changes:

In the host Rails app you've attached Locomotive to, see ```config/initializers/carrierwave.rb``` and find:

```ruby
if ENV['S3_ASSET_HOST_URL'].present?
  config.asset_host = ENV['S3_ASSET_HOST_URL']
end
```

What we're going to do is use a ```proc``` instead of a string value:

```ruby
config.asset_host = proc do |request, site|
  if site # not present when uploading via Wagon (see: ThemeAssetUploader class)
    case site.handle
    when "example-site-handle"
      "https://media.example1.com"
    when "other-site-handle"
      "https://media.example2.com"
    else #fallback on default way of setting asset host URL
      if ENV['S3_ASSET_HOST_URL'].present?
        ENV['S3_ASSET_HOST_URL']
      end
    end
  end
end
```

I hope this helps and, perhaps, it can be attached to the official documentation for others to find.

I will continue to investigate whether it's a simple fix within the Steam library. I've been investigating but testing is tough due to other constraints. It'll take a bit to wrap my head around everything.

Thanks,
Chris

**Comment by interhive** [comment]
Just an update...

I've been working on this today and have most of the changes done, for the most part. The only problem is that there are changes within steam (most of the asset_host logic), engine (UI and API changes), and wagon (API and commands).

I'll need to coordinate with someone from the LocomotiveCMS project to determine the best way of integrating these changes.

I still have a bit of testing to complete and have a few more unit tests to write. It's been interesting to test everything, to say the least.

**Comment by interhive** [comment]
As an aside, I currently have the ```asset_host``` being set within ```site.yml``` but, the more that I think of it, I'd like to get it moved to ```deploy.yml```. This would allow for different asset hosts dependent upon the deployment target (i.e. production, staging, qa, etc).

I need to figure out how steam/engine are working with these config values to make the change though... a little hung up on this right now.

**Comment by interhive** [comment]
Just a progress update... this is very nearly there. I need to do a little bit more testing but all seems to be going as expected. I am going to release this firstly as a ```site.yml``` configuration option before moving it to ```deploy.yml```.

After the initial release, hopefully someone with deeper knowledge of the project will be able to chime in and let me know what I should change to get stuff under ```deploy.yml```.

Thanks,
Chris

**Comment by did** [comment]
merged for 2 years :-) thanks again!
