### ISSUE TITLE
Net::ReadTimout in locomotivecms_wagon `1.5.8`

### ISSUE THREAD

**Issue by Arslan-Ali-Butt** [locomotivecms/wagon#339]
I'm using `locomotivecms_wagon` with version: `1.5.8`, and I want to push a lot of content to production through the following command:

    bundle exec wagon push production

I have been trying time & again, but each time, it gives the error: `Net::ReadTimeout`, and halts the process. Any workaround?

**Comment by did** [comment]
related to #318 (however Wagon 1.5.8 is deprecated)
