### ISSUE TITLE
editable_text missing

### ISSUE THREAD

**Issue by japecci** [locomotivecms/wagon#349]
Hey,

I've installed wagon on my Mac OS X 10.13
Ruby v2.3.3
Rails 4.2.8

When I serve pages I get a missing editable_text error , no problem viewing the page but when I deploy to locomotive cms I get an error that the template was not parsable and that I cannot edit online.

Downloaded project from Quickstart to check if I was doing something wrong, same problem.

MyPortfolio
Started GET "/" at 2018-05-18 14:37:52 -0400
  Params: {}
  Timezone: UTC
  Detecting locale EN
  Found page "Home page" [index]
[index] missing editable_text "jumbotron" (content/header)

**Comment by matejtaborsky** [comment]
The same here, any update on this?

**Comment by did** [comment]
I guess the installation documentation was not up to date when you read it. We're working on it.
