### ISSUE TITLE
with_scope is not filtering booleans on Wagon

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/wagon#353]
Wagon version: `gem 'locomotivecms_wagon', '~> 2.4', '>= 2.4.1'`
Engine version: 3.4.0

Here is the piece of code I am referring to. 
```
{% with_scope featured: false %}
  {% for news_item in contents.news %}
  {% endfor %}
{% endwith_scope %}
```

It works perfectly on the engine, however on wagon it doesnt. For some reason its not recognizing the boolean from the data file. `featured: false`.

If I want to make it work on wagon i need to change the data to `featured: 'false'` but then I also need to change the with_scope filter to a string `{% with_scope featured: 'false' %}` and in that case it doesnt work on the engine.

**Comment by did** [comment]
hey @DonKoko, I can't reproduce the bug with the latest commits of Wagon and Steam.

**Comment by DonKoko** [comment]
Indeed, I also haven't had the issue with newest wagon. Will let you know if I face it again.
