### ISSUE TITLE
resize filter not working

### ISSUE THREAD

**Issue by proxygear** [locomotivecms/wagon#354]
Hello,

I would like to resize an image from my public folder.
So I tried the resize filter, but it seams it does not output as expected :

I tried 

```.haml
%ul
  %li {{ "intro.jpg" | theme_image_url }}
  %li {{ "intro.jpg" | resize: "1200x650" }}
  %li {{ "intro.jpg" | theme_image_url | resize: "1200x650" }}
```

And I got

```
/images/intro.jpg
intro.jpg
/images/intro.jpg
```

So, or I haven't figured out something, or it isn't working.
The output come from the local `wagon serve`.
May be the resize isn't enabled for local service ?

Let me know, thanks.

**Comment by did** [comment]
hey @proxygear, my guess is that ImageMagick is not correctly installed. Usually, Wagon complains about it when you run `wagon serve`.
