### ISSUE TITLE
Error with listen gem unless bundle exec is used

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/wagon#361]
If you forgot to use `bundle exec` when calling `wagon serve` you get this error:

```
$ wagon serve -v

Your site is served now.
Browse http://0.0.0.0:3333


# Error description:
cannot load such file -- listen

# Backtrace:

	/home/myuser/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/locomotivecms_wagon-3.0.0.rc0/lib/locomotive/wagon/tools/listen.rb:1:in `require'
...snip...
```

That sent me on a goose chase until I realized I simply needed `bundle exec`. 

Maybe we could check if the listen gem is installed, something like:

```ruby
###  wagon/lib/locomotive/wagon/tools/listen.rb

begin
  require 'listen'
rescue LoadError => ex
  puts "Cannot find the `listen` gem. Did you forgot to use `bundle exec` when running your wagon command?".

  raise # re-raise current exception
end
```

What do you think? I would be happy to send a PR if desired.

**Comment by did** [comment]
hey @westonganger! thanks for the feedback. 
I'm looking for a way to get rid of the `bundle exec` statement because people who don't know ruby and bundle will be lost for sure.
That's not so easy. In the meantime, your suggestion makes totally sense. So go for the PR! :-) 
Thanks!
