### ISSUE TITLE
Error when app/views/pages/content_type_template.liquid is present

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/wagon#362]
The page wouldnt load with a Steam error:

```
#<NoMethodError: undefined method `_label' for nil:NilClass>
  Error: undefined method `_label' for nil:NilClass
  /home/myuser/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/liquid/tags/link_to.rb:36:in `label_from_page'
```

To fix I had to delete folders and files until I found which one was the culprit. 

Turns out I accidentally placed a `content_type_template.liquid ` file at `app/views/pages/content_type_template.liquid` Once I removed this file the site loaded correctly again.

This was a super unhelpful error message for this case. Wouldve been better if we raised a more specific error in cases like this.

**Comment by did** [comment]
Interesting. Placing content_type_template.liquid at the root folder might be sometimes the expected behavior. Except in your case :-)  Do you have the full stack trace of the error? 
Thanks!

**Comment by westonganger** [comment]
Sorry im having trouble reproducing this issue. It seems to be working correctly now. Feel free to close.
