### ISSUE TITLE
Wagon layout names convert underscores to dashes by default

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/wagon#363]
I created a layout `bootstrap_company.liquid.haml` and tried to use it:
```
{% extends 'layouts/bootstrap_company' %}
```

but my project kept complaining that it couldnt find the layout. After a while of debugging I decided to try dashes instead of underscores in the extends and it worked. Ex.

```
{% extends 'layouts/bootstrap-company' %}
```
To solve this I had to manually define the layouts slug attribute:

```
---
title: Boostrap Company
slug: bootstrap_company
is_layout: true
---
```

 I was not expecting this behaviour at all. I would appreciate if it didnt convert my underscores to dashes.

Also I did not find any documentation relating to this. Would appreciate mentioning the layouts slug in the documentation.

**Comment by did** [comment]
Thanks! Let me add this in the documentation!

**Comment by did** [comment]
See the orange callout [here](https://doc.locomotivecms.com/v4.0/docs/create-a-page)
