### ISSUE TITLE
Should be able to deploy new sites via Wagon tool

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/wagon#366]
It would be really nice to be able to deploy sites directly from the wagon cli. For simplicity, maybe this could be restricted to `super_admin` users only?

`option :create_site, aliases: '-c', type: 'boolean', default: false, desc: 'Create the site if it does not already exist. Requires create site permissions.'`

**Comment by did** [comment]
Well, this feature is already present in the current version of Wagon. All you have to do is to run `wagon auth` as described here (https://doc.locomotivecms.com/docs/commands).
And at the first `wagon deploy` command execution, Wagon will call Engine to create the site.
For some reason, I prefer to create it manually, no valid reason for doing that :-)

**Comment by westonganger** [comment]
Ok. Then if that is the case I have two suggestions here:

1. When not auth'ed, trying to deploy a new site, when it errors add a message like `if you would like to deploy a new site please first login using the "wagon auth" command`
2. When deploying a new site can you add a shell warning like `You are about to deploy a new site. Are you sure you want to perform this action?`
