### ISSUE TITLE
Add are you sure warning when using wagon deploy -d option

### ISSUE THREAD

**Issue by westonganger** [locomotivecms/wagon#367]
Since the `-d` performs the site seeds it would be nice to have an are you sure prompt. This would prevent accidentally seeding on existing sites that only needed the code updated.

**Comment by manuchap** [comment]
Please! Is there a way do disable this? Like a "super dev" or "I know what I'm doing" mode? I really like the sound of my keyboard but I really could do without those extra steps a few dozens time a day...
