### ISSUE TITLE
Allow to push wagons to a Basic Http Auth Staging Site

### ISSUE THREAD

**Issue by silvermind** [locomotivecms/wagon#81]
Our LocomotiveCMS Staging Host use a Basic Authentication Password to block access to 
sites.

I've tried various host values in the deploy.yml file without luck. Is there a way to allow wagon pushes to a Basic Auth protected host?

``` ruby
staging:
  host: http://user:password@subdomain.cms-host.domain
  api_key: ...
```

**Comment by jo-m** [comment]
what is the status of this? Does it work now, and if yes, how?

**Comment by silvermind** [comment]
not sure, have never setup the staging server finally. only production :)

**Comment by jo-m** [comment]
ok... our staging server now just uses an nginx config which puts everything except static files and api behind HTTP Basic Auth.
