### ISSUE TITLE
Guard livereload

### ISSUE THREAD

**Issue by joaovpmamede** [locomotivecms/wagon#98]
I've tried running these gems:

guard
guard-livereload
rack-livereload

For the changes on liquid templates(html) everythings works fine but the ones on the css don't trigger the style injection
I've been looking at this link [Lightning fast sass reloading in rails](http://blog.55minutes.com/2013/01/lightning-fast-sass-reloading-in-rails-32/)

So do you guys develop with livereload? Do you have the style injection?

**Comment by gregory** [comment]
Anyone have been able to get livereload to work?

**Comment by ccmeyers** [comment]
Livereload works now with guard. 
Add gem 'guard-livereload' to your gemfile
Run 'bundle install' and then 'guard init livereload' in your terminal to create your Guardfile
At the bottom of your Guardfile, include watching for 'liquid' and scss/sass/less/etc if need be, like below: 
```
guard 'livereload' do
  watch(%r{app/views/.+\.(erb|haml|slim|liquid)$})
  watch(%r{app/helpers/.+\.rb})
  watch(%r{public/.+\.(css|js|html|scss)})
  watch(%r{config/locales/.+\.yml})
  # Rails Assets Pipeline
  watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html|png|jpg))).*}) { |m| "/assets/#{m[3]}" }
end
```
Run 'guard' in your terminal to start watching (while using a livereload browser extension)

**Comment by did** [comment]
included in Wagon v2 (https://locomotive-v3.readme.io/docs/preview-locally)
